// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_logs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewLog = `-- name: CreateReviewLog :one

INSERT INTO review_logs (id, card_id, user_id, grade, prev_state, duration_ms, reviewed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, card_id, user_id, grade, prev_state, duration_ms, reviewed_at
`

type CreateReviewLogParams struct {
	ID         uuid.UUID
	CardID     uuid.UUID
	UserID     uuid.UUID
	Grade      ReviewGrade
	PrevState  []byte
	DurationMs pgtype.Int4
	ReviewedAt time.Time
}

type CreateReviewLogRow struct {
	ID         uuid.UUID
	CardID     uuid.UUID
	UserID     uuid.UUID
	Grade      ReviewGrade
	PrevState  []byte
	DurationMs pgtype.Int4
	ReviewedAt time.Time
}

// ---------------------------------------------------------------------------
// review_logs
// ---------------------------------------------------------------------------
func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (CreateReviewLogRow, error) {
	row := q.db.QueryRow(ctx, createReviewLog,
		arg.ID,
		arg.CardID,
		arg.UserID,
		arg.Grade,
		arg.PrevState,
		arg.DurationMs,
		arg.ReviewedAt,
	)
	var i CreateReviewLogRow
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Grade,
		&i.PrevState,
		&i.DurationMs,
		&i.ReviewedAt,
	)
	return i, err
}

const deleteReviewLog = `-- name: DeleteReviewLog :execrows
DELETE FROM review_logs
WHERE id = $1
`

func (q *Queries) DeleteReviewLog(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReviewLog, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getByCardID = `-- name: GetByCardID :many
SELECT id, card_id, user_id, grade, prev_state, duration_ms, reviewed_at
FROM review_logs
WHERE card_id = $1
ORDER BY reviewed_at DESC
LIMIT $3::int OFFSET $2::int
`

type GetByCardIDParams struct {
	CardID uuid.UUID
	Off    int32
	Lim    int32
}

type GetByCardIDRow struct {
	ID         uuid.UUID
	CardID     uuid.UUID
	UserID     uuid.UUID
	Grade      ReviewGrade
	PrevState  []byte
	DurationMs pgtype.Int4
	ReviewedAt time.Time
}

func (q *Queries) GetByCardID(ctx context.Context, arg GetByCardIDParams) ([]GetByCardIDRow, error) {
	rows, err := q.db.Query(ctx, getByCardID, arg.CardID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetByCardIDRow{}
	for rows.Next() {
		var i GetByCardIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Grade,
			&i.PrevState,
			&i.DurationMs,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastByCardID = `-- name: GetLastByCardID :one
SELECT id, card_id, user_id, grade, prev_state, duration_ms, reviewed_at
FROM review_logs
WHERE card_id = $1
ORDER BY reviewed_at DESC
LIMIT 1
`

type GetLastByCardIDRow struct {
	ID         uuid.UUID
	CardID     uuid.UUID
	UserID     uuid.UUID
	Grade      ReviewGrade
	PrevState  []byte
	DurationMs pgtype.Int4
	ReviewedAt time.Time
}

func (q *Queries) GetLastByCardID(ctx context.Context, cardID uuid.UUID) (GetLastByCardIDRow, error) {
	row := q.db.QueryRow(ctx, getLastByCardID, cardID)
	var i GetLastByCardIDRow
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.UserID,
		&i.Grade,
		&i.PrevState,
		&i.DurationMs,
		&i.ReviewedAt,
	)
	return i, err
}
