// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package inbox

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that inboxRepoMock does implement inboxRepo.
// If this is not the case, regenerate this file with moq.
var _ inboxRepo = &inboxRepoMock{}

// inboxRepoMock is a mock implementation of inboxRepo.
//
//	func TestSomethingThatUsesinboxRepo(t *testing.T) {
//
//		// make and configure a mocked inboxRepo
//		mockedinboxRepo := &inboxRepoMock{
//			CountFunc: func(ctx context.Context, userID uuid.UUID) (int, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, userID uuid.UUID, item *domain.InboxItem) (*domain.InboxItem, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			DeleteAllFunc: func(ctx context.Context, userID uuid.UUID) (int, error) {
//				panic("mock out the DeleteAll method")
//			},
//			GetByIDFunc: func(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) (*domain.InboxItem, error) {
//				panic("mock out the GetByID method")
//			},
//			ListFunc: func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.InboxItem, int, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedinboxRepo in code that requires inboxRepo
//		// and then make assertions.
//
//	}
type inboxRepoMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, userID uuid.UUID) (int, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, userID uuid.UUID, item *domain.InboxItem) (*domain.InboxItem, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) error

	// DeleteAllFunc mocks the DeleteAll method.
	DeleteAllFunc func(ctx context.Context, userID uuid.UUID) (int, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) (*domain.InboxItem, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.InboxItem, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Item is the item argument value.
			Item *domain.InboxItem
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ItemID is the itemID argument value.
			ItemID uuid.UUID
		}
		// DeleteAll holds details about calls to the DeleteAll method.
		DeleteAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// ItemID is the itemID argument value.
			ItemID uuid.UUID
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
	}
	lockCount     sync.RWMutex
	lockCreate    sync.RWMutex
	lockDelete    sync.RWMutex
	lockDeleteAll sync.RWMutex
	lockGetByID   sync.RWMutex
	lockList      sync.RWMutex
}

// Count calls CountFunc.
func (mock *inboxRepoMock) Count(ctx context.Context, userID uuid.UUID) (int, error) {
	if mock.CountFunc == nil {
		panic("inboxRepoMock.CountFunc: method is nil but inboxRepo.Count was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, userID)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedinboxRepo.CountCalls())
func (mock *inboxRepoMock) CountCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *inboxRepoMock) Create(ctx context.Context, userID uuid.UUID, item *domain.InboxItem) (*domain.InboxItem, error) {
	if mock.CreateFunc == nil {
		panic("inboxRepoMock.CreateFunc: method is nil but inboxRepo.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		Item   *domain.InboxItem
	}{
		Ctx:    ctx,
		UserID: userID,
		Item:   item,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, userID, item)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedinboxRepo.CreateCalls())
func (mock *inboxRepoMock) CreateCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	Item   *domain.InboxItem
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		Item   *domain.InboxItem
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *inboxRepoMock) Delete(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("inboxRepoMock.DeleteFunc: method is nil but inboxRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		ItemID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
		ItemID: itemID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, userID, itemID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedinboxRepo.DeleteCalls())
func (mock *inboxRepoMock) DeleteCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	ItemID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		ItemID uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteAll calls DeleteAllFunc.
func (mock *inboxRepoMock) DeleteAll(ctx context.Context, userID uuid.UUID) (int, error) {
	if mock.DeleteAllFunc == nil {
		panic("inboxRepoMock.DeleteAllFunc: method is nil but inboxRepo.DeleteAll was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDeleteAll.Lock()
	mock.calls.DeleteAll = append(mock.calls.DeleteAll, callInfo)
	mock.lockDeleteAll.Unlock()
	return mock.DeleteAllFunc(ctx, userID)
}

// DeleteAllCalls gets all the calls that were made to DeleteAll.
// Check the length with:
//
//	len(mockedinboxRepo.DeleteAllCalls())
func (mock *inboxRepoMock) DeleteAllCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockDeleteAll.RLock()
	calls = mock.calls.DeleteAll
	mock.lockDeleteAll.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *inboxRepoMock) GetByID(ctx context.Context, userID uuid.UUID, itemID uuid.UUID) (*domain.InboxItem, error) {
	if mock.GetByIDFunc == nil {
		panic("inboxRepoMock.GetByIDFunc: method is nil but inboxRepo.GetByID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		ItemID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
		ItemID: itemID,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, userID, itemID)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedinboxRepo.GetByIDCalls())
func (mock *inboxRepoMock) GetByIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	ItemID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		ItemID uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *inboxRepoMock) List(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*domain.InboxItem, int, error) {
	if mock.ListFunc == nil {
		panic("inboxRepoMock.ListFunc: method is nil but inboxRepo.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		UserID: userID,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, userID, limit, offset)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedinboxRepo.ListCalls())
func (mock *inboxRepoMock) ListCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
