// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package middleware

import (
	"context"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that tokenValidatorMock does implement tokenValidator.
// If this is not the case, regenerate this file with moq.
var _ tokenValidator = &tokenValidatorMock{}

// tokenValidatorMock is a mock implementation of tokenValidator.
//
//	func TestSomethingThatUsestokenValidator(t *testing.T) {
//
//		// make and configure a mocked tokenValidator
//		mockedtokenValidator := &tokenValidatorMock{
//			ValidateTokenFunc: func(ctx context.Context, token string) (uuid.UUID, error) {
//				panic("mock out the ValidateToken method")
//			},
//		}
//
//		// use mockedtokenValidator in code that requires tokenValidator
//		// and then make assertions.
//
//	}
type tokenValidatorMock struct {
	// ValidateTokenFunc mocks the ValidateToken method.
	ValidateTokenFunc func(ctx context.Context, token string) (uuid.UUID, error)

	// calls tracks calls to the methods.
	calls struct {
		// ValidateToken holds details about calls to the ValidateToken method.
		ValidateToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockValidateToken sync.RWMutex
}

// ValidateToken calls ValidateTokenFunc.
func (mock *tokenValidatorMock) ValidateToken(ctx context.Context, token string) (uuid.UUID, error) {
	if mock.ValidateTokenFunc == nil {
		panic("tokenValidatorMock.ValidateTokenFunc: method is nil but tokenValidator.ValidateToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockValidateToken.Lock()
	mock.calls.ValidateToken = append(mock.calls.ValidateToken, callInfo)
	mock.lockValidateToken.Unlock()
	return mock.ValidateTokenFunc(ctx, token)
}

// ValidateTokenCalls gets all the calls that were made to ValidateToken.
// Check the length with:
//
//	len(mockedtokenValidator.ValidateTokenCalls())
func (mock *tokenValidatorMock) ValidateTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockValidateToken.RLock()
	calls = mock.calls.ValidateToken
	mock.lockValidateToken.RUnlock()
	return calls
}
