// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBySense = `-- name: CountBySense :one
SELECT count(*) FROM translations WHERE sense_id = $1
`

func (q *Queries) CountBySense(ctx context.Context, senseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBySense, senseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTranslationCustom = `-- name: CreateTranslationCustom :one
INSERT INTO translations (id, sense_id, text, source_slug, position)
VALUES ($1, $2, $3, $4, COALESCE((SELECT MAX(position) FROM translations WHERE sense_id = $2), -1) + 1)
RETURNING id, sense_id, ref_translation_id, text, source_slug, position
`

type CreateTranslationCustomParams struct {
	ID         uuid.UUID
	SenseID    uuid.UUID
	Text       pgtype.Text
	SourceSlug string
}

func (q *Queries) CreateTranslationCustom(ctx context.Context, arg CreateTranslationCustomParams) (Translation, error) {
	row := q.db.QueryRow(ctx, createTranslationCustom,
		arg.ID,
		arg.SenseID,
		arg.Text,
		arg.SourceSlug,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.SenseID,
		&i.RefTranslationID,
		&i.Text,
		&i.SourceSlug,
		&i.Position,
	)
	return i, err
}

const createTranslationFromRef = `-- name: CreateTranslationFromRef :one
INSERT INTO translations (id, sense_id, ref_translation_id, source_slug, position)
VALUES ($1, $2, $3, $4, COALESCE((SELECT MAX(position) FROM translations WHERE sense_id = $2), -1) + 1)
RETURNING id, sense_id, ref_translation_id, text, source_slug, position
`

type CreateTranslationFromRefParams struct {
	ID               uuid.UUID
	SenseID          uuid.UUID
	RefTranslationID pgtype.UUID
	SourceSlug       string
}

func (q *Queries) CreateTranslationFromRef(ctx context.Context, arg CreateTranslationFromRefParams) (Translation, error) {
	row := q.db.QueryRow(ctx, createTranslationFromRef,
		arg.ID,
		arg.SenseID,
		arg.RefTranslationID,
		arg.SourceSlug,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.SenseID,
		&i.RefTranslationID,
		&i.Text,
		&i.SourceSlug,
		&i.Position,
	)
	return i, err
}

const deleteTranslation = `-- name: DeleteTranslation :execrows
DELETE FROM translations WHERE id = $1
`

func (q *Queries) DeleteTranslation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTranslation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTranslation = `-- name: UpdateTranslation :one
UPDATE translations
SET text = $2
WHERE id = $1
RETURNING id, sense_id, ref_translation_id, text, source_slug, position
`

type UpdateTranslationParams struct {
	ID   uuid.UUID
	Text pgtype.Text
}

func (q *Queries) UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, updateTranslation, arg.ID, arg.Text)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.SenseID,
		&i.RefTranslationID,
		&i.Text,
		&i.SourceSlug,
		&i.Position,
	)
	return i, err
}

const updateTranslationPosition = `-- name: UpdateTranslationPosition :exec
UPDATE translations SET position = $2 WHERE id = $1
`

type UpdateTranslationPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateTranslationPosition(ctx context.Context, arg UpdateTranslationPositionParams) error {
	_, err := q.db.Exec(ctx, updateTranslationPosition, arg.ID, arg.Position)
	return err
}
