// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coverage.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getCoverageByEntryID = `-- name: GetCoverageByEntryID :many

SELECT ref_entry_id, source_slug, status, dataset_version, fetched_at
FROM ref_entry_source_coverage
WHERE ref_entry_id = $1
ORDER BY source_slug
`

// ---------------------------------------------------------------------------
// ref_entry_source_coverage
// ---------------------------------------------------------------------------
func (q *Queries) GetCoverageByEntryID(ctx context.Context, refEntryID uuid.UUID) ([]RefEntrySourceCoverage, error) {
	rows, err := q.db.Query(ctx, getCoverageByEntryID, refEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefEntrySourceCoverage{}
	for rows.Next() {
		var i RefEntrySourceCoverage
		if err := rows.Scan(
			&i.RefEntryID,
			&i.SourceSlug,
			&i.Status,
			&i.DatasetVersion,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoverageByEntryIDs = `-- name: GetCoverageByEntryIDs :many
SELECT ref_entry_id, source_slug, status, dataset_version, fetched_at
FROM ref_entry_source_coverage
WHERE ref_entry_id = ANY($1::uuid[])
ORDER BY ref_entry_id, source_slug
`

func (q *Queries) GetCoverageByEntryIDs(ctx context.Context, entryIds []uuid.UUID) ([]RefEntrySourceCoverage, error) {
	rows, err := q.db.Query(ctx, getCoverageByEntryIDs, entryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefEntrySourceCoverage{}
	for rows.Next() {
		var i RefEntrySourceCoverage
		if err := rows.Scan(
			&i.RefEntryID,
			&i.SourceSlug,
			&i.Status,
			&i.DatasetVersion,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
