// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: datasource.sql

package sqlc

import (
	"context"
)

const getAllDataSources = `-- name: GetAllDataSources :many

SELECT slug, name, description, source_type, is_active, dataset_version, created_at, updated_at
FROM ref_data_sources
WHERE is_active = true
ORDER BY slug
`

// ---------------------------------------------------------------------------
// ref_data_sources
// ---------------------------------------------------------------------------
func (q *Queries) GetAllDataSources(ctx context.Context) ([]RefDataSource, error) {
	rows, err := q.db.Query(ctx, getAllDataSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefDataSource{}
	for rows.Next() {
		var i RefDataSource
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.IsActive,
			&i.DatasetVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataSourceBySlug = `-- name: GetDataSourceBySlug :one
SELECT slug, name, description, source_type, is_active, dataset_version, created_at, updated_at
FROM ref_data_sources
WHERE slug = $1
`

func (q *Queries) GetDataSourceBySlug(ctx context.Context, slug string) (RefDataSource, error) {
	row := q.db.QueryRow(ctx, getDataSourceBySlug, slug)
	var i RefDataSource
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.IsActive,
		&i.DatasetVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
