// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getRelationsByEntryID = `-- name: GetRelationsByEntryID :many

SELECT id, source_entry_id, target_entry_id, relation_type, source_slug, created_at
FROM ref_word_relations
WHERE source_entry_id = $1 OR target_entry_id = $1
ORDER BY relation_type, created_at
`

// ---------------------------------------------------------------------------
// ref_word_relations
// ---------------------------------------------------------------------------
func (q *Queries) GetRelationsByEntryID(ctx context.Context, sourceEntryID uuid.UUID) ([]RefWordRelation, error) {
	rows, err := q.db.Query(ctx, getRelationsByEntryID, sourceEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefWordRelation{}
	for rows.Next() {
		var i RefWordRelation
		if err := rows.Scan(
			&i.ID,
			&i.SourceEntryID,
			&i.TargetEntryID,
			&i.RelationType,
			&i.SourceSlug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
