package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/transport/graphql/generated"
)

// AddSense is the resolver for the addSense field.
func (r *mutationResolver) AddSense(ctx context.Context, input generated.AddSenseInput) (*generated.AddSensePayload, error) {
	panic(fmt.Errorf("not implemented: AddSense - addSense"))
}

// UpdateSense is the resolver for the updateSense field.
func (r *mutationResolver) UpdateSense(ctx context.Context, input generated.UpdateSenseInput) (*generated.UpdateSensePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateSense - updateSense"))
}

// DeleteSense is the resolver for the deleteSense field.
func (r *mutationResolver) DeleteSense(ctx context.Context, id uuid.UUID) (*generated.DeleteSensePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteSense - deleteSense"))
}

// ReorderSenses is the resolver for the reorderSenses field.
func (r *mutationResolver) ReorderSenses(ctx context.Context, input generated.ReorderSensesInput) (*generated.ReorderPayload, error) {
	panic(fmt.Errorf("not implemented: ReorderSenses - reorderSenses"))
}

// AddTranslation is the resolver for the addTranslation field.
func (r *mutationResolver) AddTranslation(ctx context.Context, input generated.AddTranslationInput) (*generated.AddTranslationPayload, error) {
	panic(fmt.Errorf("not implemented: AddTranslation - addTranslation"))
}

// UpdateTranslation is the resolver for the updateTranslation field.
func (r *mutationResolver) UpdateTranslation(ctx context.Context, input generated.UpdateTranslationInput) (*generated.UpdateTranslationPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateTranslation - updateTranslation"))
}

// DeleteTranslation is the resolver for the deleteTranslation field.
func (r *mutationResolver) DeleteTranslation(ctx context.Context, id uuid.UUID) (*generated.DeleteTranslationPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteTranslation - deleteTranslation"))
}

// ReorderTranslations is the resolver for the reorderTranslations field.
func (r *mutationResolver) ReorderTranslations(ctx context.Context, input generated.ReorderTranslationsInput) (*generated.ReorderPayload, error) {
	panic(fmt.Errorf("not implemented: ReorderTranslations - reorderTranslations"))
}

// AddExample is the resolver for the addExample field.
func (r *mutationResolver) AddExample(ctx context.Context, input generated.AddExampleInput) (*generated.AddExamplePayload, error) {
	panic(fmt.Errorf("not implemented: AddExample - addExample"))
}

// UpdateExample is the resolver for the updateExample field.
func (r *mutationResolver) UpdateExample(ctx context.Context, input generated.UpdateExampleInput) (*generated.UpdateExamplePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateExample - updateExample"))
}

// DeleteExample is the resolver for the deleteExample field.
func (r *mutationResolver) DeleteExample(ctx context.Context, id uuid.UUID) (*generated.DeleteExamplePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteExample - deleteExample"))
}

// ReorderExamples is the resolver for the reorderExamples field.
func (r *mutationResolver) ReorderExamples(ctx context.Context, input generated.ReorderExamplesInput) (*generated.ReorderPayload, error) {
	panic(fmt.Errorf("not implemented: ReorderExamples - reorderExamples"))
}

// AddUserImage is the resolver for the addUserImage field.
func (r *mutationResolver) AddUserImage(ctx context.Context, input generated.AddUserImageInput) (*generated.AddUserImagePayload, error) {
	panic(fmt.Errorf("not implemented: AddUserImage - addUserImage"))
}

// DeleteUserImage is the resolver for the deleteUserImage field.
func (r *mutationResolver) DeleteUserImage(ctx context.Context, id uuid.UUID) (*generated.DeleteUserImagePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteUserImage - deleteUserImage"))
}
