// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resolver

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"github.com/heartmarshall/myenglish-backend/internal/service/content"
	"sync"
)

// Ensure, that contentServiceMock does implement contentService.
// If this is not the case, regenerate this file with moq.
var _ contentService = &contentServiceMock{}

// contentServiceMock is a mock implementation of contentService.
//
//	func TestSomethingThatUsescontentService(t *testing.T) {
//
//		// make and configure a mocked contentService
//		mockedcontentService := &contentServiceMock{
//			AddExampleFunc: func(ctx context.Context, input content.AddExampleInput) (*domain.Example, error) {
//				panic("mock out the AddExample method")
//			},
//			AddSenseFunc: func(ctx context.Context, input content.AddSenseInput) (*domain.Sense, error) {
//				panic("mock out the AddSense method")
//			},
//			AddTranslationFunc: func(ctx context.Context, input content.AddTranslationInput) (*domain.Translation, error) {
//				panic("mock out the AddTranslation method")
//			},
//			AddUserImageFunc: func(ctx context.Context, input content.AddUserImageInput) (*domain.UserImage, error) {
//				panic("mock out the AddUserImage method")
//			},
//			DeleteExampleFunc: func(ctx context.Context, exampleID uuid.UUID) error {
//				panic("mock out the DeleteExample method")
//			},
//			DeleteSenseFunc: func(ctx context.Context, senseID uuid.UUID) error {
//				panic("mock out the DeleteSense method")
//			},
//			DeleteTranslationFunc: func(ctx context.Context, translationID uuid.UUID) error {
//				panic("mock out the DeleteTranslation method")
//			},
//			DeleteUserImageFunc: func(ctx context.Context, imageID uuid.UUID) error {
//				panic("mock out the DeleteUserImage method")
//			},
//			ReorderExamplesFunc: func(ctx context.Context, input content.ReorderExamplesInput) error {
//				panic("mock out the ReorderExamples method")
//			},
//			ReorderSensesFunc: func(ctx context.Context, input content.ReorderSensesInput) error {
//				panic("mock out the ReorderSenses method")
//			},
//			ReorderTranslationsFunc: func(ctx context.Context, input content.ReorderTranslationsInput) error {
//				panic("mock out the ReorderTranslations method")
//			},
//			UpdateExampleFunc: func(ctx context.Context, input content.UpdateExampleInput) (*domain.Example, error) {
//				panic("mock out the UpdateExample method")
//			},
//			UpdateSenseFunc: func(ctx context.Context, input content.UpdateSenseInput) (*domain.Sense, error) {
//				panic("mock out the UpdateSense method")
//			},
//			UpdateTranslationFunc: func(ctx context.Context, input content.UpdateTranslationInput) (*domain.Translation, error) {
//				panic("mock out the UpdateTranslation method")
//			},
//		}
//
//		// use mockedcontentService in code that requires contentService
//		// and then make assertions.
//
//	}
type contentServiceMock struct {
	// AddExampleFunc mocks the AddExample method.
	AddExampleFunc func(ctx context.Context, input content.AddExampleInput) (*domain.Example, error)

	// AddSenseFunc mocks the AddSense method.
	AddSenseFunc func(ctx context.Context, input content.AddSenseInput) (*domain.Sense, error)

	// AddTranslationFunc mocks the AddTranslation method.
	AddTranslationFunc func(ctx context.Context, input content.AddTranslationInput) (*domain.Translation, error)

	// AddUserImageFunc mocks the AddUserImage method.
	AddUserImageFunc func(ctx context.Context, input content.AddUserImageInput) (*domain.UserImage, error)

	// DeleteExampleFunc mocks the DeleteExample method.
	DeleteExampleFunc func(ctx context.Context, exampleID uuid.UUID) error

	// DeleteSenseFunc mocks the DeleteSense method.
	DeleteSenseFunc func(ctx context.Context, senseID uuid.UUID) error

	// DeleteTranslationFunc mocks the DeleteTranslation method.
	DeleteTranslationFunc func(ctx context.Context, translationID uuid.UUID) error

	// DeleteUserImageFunc mocks the DeleteUserImage method.
	DeleteUserImageFunc func(ctx context.Context, imageID uuid.UUID) error

	// ReorderExamplesFunc mocks the ReorderExamples method.
	ReorderExamplesFunc func(ctx context.Context, input content.ReorderExamplesInput) error

	// ReorderSensesFunc mocks the ReorderSenses method.
	ReorderSensesFunc func(ctx context.Context, input content.ReorderSensesInput) error

	// ReorderTranslationsFunc mocks the ReorderTranslations method.
	ReorderTranslationsFunc func(ctx context.Context, input content.ReorderTranslationsInput) error

	// UpdateExampleFunc mocks the UpdateExample method.
	UpdateExampleFunc func(ctx context.Context, input content.UpdateExampleInput) (*domain.Example, error)

	// UpdateSenseFunc mocks the UpdateSense method.
	UpdateSenseFunc func(ctx context.Context, input content.UpdateSenseInput) (*domain.Sense, error)

	// UpdateTranslationFunc mocks the UpdateTranslation method.
	UpdateTranslationFunc func(ctx context.Context, input content.UpdateTranslationInput) (*domain.Translation, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddExample holds details about calls to the AddExample method.
		AddExample []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.AddExampleInput
		}
		// AddSense holds details about calls to the AddSense method.
		AddSense []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.AddSenseInput
		}
		// AddTranslation holds details about calls to the AddTranslation method.
		AddTranslation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.AddTranslationInput
		}
		// AddUserImage holds details about calls to the AddUserImage method.
		AddUserImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.AddUserImageInput
		}
		// DeleteExample holds details about calls to the DeleteExample method.
		DeleteExample []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ExampleID is the exampleID argument value.
			ExampleID uuid.UUID
		}
		// DeleteSense holds details about calls to the DeleteSense method.
		DeleteSense []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SenseID is the senseID argument value.
			SenseID uuid.UUID
		}
		// DeleteTranslation holds details about calls to the DeleteTranslation method.
		DeleteTranslation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TranslationID is the translationID argument value.
			TranslationID uuid.UUID
		}
		// DeleteUserImage holds details about calls to the DeleteUserImage method.
		DeleteUserImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ImageID is the imageID argument value.
			ImageID uuid.UUID
		}
		// ReorderExamples holds details about calls to the ReorderExamples method.
		ReorderExamples []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.ReorderExamplesInput
		}
		// ReorderSenses holds details about calls to the ReorderSenses method.
		ReorderSenses []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.ReorderSensesInput
		}
		// ReorderTranslations holds details about calls to the ReorderTranslations method.
		ReorderTranslations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.ReorderTranslationsInput
		}
		// UpdateExample holds details about calls to the UpdateExample method.
		UpdateExample []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.UpdateExampleInput
		}
		// UpdateSense holds details about calls to the UpdateSense method.
		UpdateSense []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.UpdateSenseInput
		}
		// UpdateTranslation holds details about calls to the UpdateTranslation method.
		UpdateTranslation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input content.UpdateTranslationInput
		}
	}
	lockAddExample          sync.RWMutex
	lockAddSense            sync.RWMutex
	lockAddTranslation      sync.RWMutex
	lockAddUserImage        sync.RWMutex
	lockDeleteExample       sync.RWMutex
	lockDeleteSense         sync.RWMutex
	lockDeleteTranslation   sync.RWMutex
	lockDeleteUserImage     sync.RWMutex
	lockReorderExamples     sync.RWMutex
	lockReorderSenses       sync.RWMutex
	lockReorderTranslations sync.RWMutex
	lockUpdateExample       sync.RWMutex
	lockUpdateSense         sync.RWMutex
	lockUpdateTranslation   sync.RWMutex
}

// AddExample calls AddExampleFunc.
func (mock *contentServiceMock) AddExample(ctx context.Context, input content.AddExampleInput) (*domain.Example, error) {
	if mock.AddExampleFunc == nil {
		panic("contentServiceMock.AddExampleFunc: method is nil but contentService.AddExample was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.AddExampleInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockAddExample.Lock()
	mock.calls.AddExample = append(mock.calls.AddExample, callInfo)
	mock.lockAddExample.Unlock()
	return mock.AddExampleFunc(ctx, input)
}

// AddExampleCalls gets all the calls that were made to AddExample.
// Check the length with:
//
//	len(mockedcontentService.AddExampleCalls())
func (mock *contentServiceMock) AddExampleCalls() []struct {
	Ctx   context.Context
	Input content.AddExampleInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.AddExampleInput
	}
	mock.lockAddExample.RLock()
	calls = mock.calls.AddExample
	mock.lockAddExample.RUnlock()
	return calls
}

// AddSense calls AddSenseFunc.
func (mock *contentServiceMock) AddSense(ctx context.Context, input content.AddSenseInput) (*domain.Sense, error) {
	if mock.AddSenseFunc == nil {
		panic("contentServiceMock.AddSenseFunc: method is nil but contentService.AddSense was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.AddSenseInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockAddSense.Lock()
	mock.calls.AddSense = append(mock.calls.AddSense, callInfo)
	mock.lockAddSense.Unlock()
	return mock.AddSenseFunc(ctx, input)
}

// AddSenseCalls gets all the calls that were made to AddSense.
// Check the length with:
//
//	len(mockedcontentService.AddSenseCalls())
func (mock *contentServiceMock) AddSenseCalls() []struct {
	Ctx   context.Context
	Input content.AddSenseInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.AddSenseInput
	}
	mock.lockAddSense.RLock()
	calls = mock.calls.AddSense
	mock.lockAddSense.RUnlock()
	return calls
}

// AddTranslation calls AddTranslationFunc.
func (mock *contentServiceMock) AddTranslation(ctx context.Context, input content.AddTranslationInput) (*domain.Translation, error) {
	if mock.AddTranslationFunc == nil {
		panic("contentServiceMock.AddTranslationFunc: method is nil but contentService.AddTranslation was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.AddTranslationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockAddTranslation.Lock()
	mock.calls.AddTranslation = append(mock.calls.AddTranslation, callInfo)
	mock.lockAddTranslation.Unlock()
	return mock.AddTranslationFunc(ctx, input)
}

// AddTranslationCalls gets all the calls that were made to AddTranslation.
// Check the length with:
//
//	len(mockedcontentService.AddTranslationCalls())
func (mock *contentServiceMock) AddTranslationCalls() []struct {
	Ctx   context.Context
	Input content.AddTranslationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.AddTranslationInput
	}
	mock.lockAddTranslation.RLock()
	calls = mock.calls.AddTranslation
	mock.lockAddTranslation.RUnlock()
	return calls
}

// AddUserImage calls AddUserImageFunc.
func (mock *contentServiceMock) AddUserImage(ctx context.Context, input content.AddUserImageInput) (*domain.UserImage, error) {
	if mock.AddUserImageFunc == nil {
		panic("contentServiceMock.AddUserImageFunc: method is nil but contentService.AddUserImage was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.AddUserImageInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockAddUserImage.Lock()
	mock.calls.AddUserImage = append(mock.calls.AddUserImage, callInfo)
	mock.lockAddUserImage.Unlock()
	return mock.AddUserImageFunc(ctx, input)
}

// AddUserImageCalls gets all the calls that were made to AddUserImage.
// Check the length with:
//
//	len(mockedcontentService.AddUserImageCalls())
func (mock *contentServiceMock) AddUserImageCalls() []struct {
	Ctx   context.Context
	Input content.AddUserImageInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.AddUserImageInput
	}
	mock.lockAddUserImage.RLock()
	calls = mock.calls.AddUserImage
	mock.lockAddUserImage.RUnlock()
	return calls
}

// DeleteExample calls DeleteExampleFunc.
func (mock *contentServiceMock) DeleteExample(ctx context.Context, exampleID uuid.UUID) error {
	if mock.DeleteExampleFunc == nil {
		panic("contentServiceMock.DeleteExampleFunc: method is nil but contentService.DeleteExample was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ExampleID uuid.UUID
	}{
		Ctx:       ctx,
		ExampleID: exampleID,
	}
	mock.lockDeleteExample.Lock()
	mock.calls.DeleteExample = append(mock.calls.DeleteExample, callInfo)
	mock.lockDeleteExample.Unlock()
	return mock.DeleteExampleFunc(ctx, exampleID)
}

// DeleteExampleCalls gets all the calls that were made to DeleteExample.
// Check the length with:
//
//	len(mockedcontentService.DeleteExampleCalls())
func (mock *contentServiceMock) DeleteExampleCalls() []struct {
	Ctx       context.Context
	ExampleID uuid.UUID
} {
	var calls []struct {
		Ctx       context.Context
		ExampleID uuid.UUID
	}
	mock.lockDeleteExample.RLock()
	calls = mock.calls.DeleteExample
	mock.lockDeleteExample.RUnlock()
	return calls
}

// DeleteSense calls DeleteSenseFunc.
func (mock *contentServiceMock) DeleteSense(ctx context.Context, senseID uuid.UUID) error {
	if mock.DeleteSenseFunc == nil {
		panic("contentServiceMock.DeleteSenseFunc: method is nil but contentService.DeleteSense was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		SenseID uuid.UUID
	}{
		Ctx:     ctx,
		SenseID: senseID,
	}
	mock.lockDeleteSense.Lock()
	mock.calls.DeleteSense = append(mock.calls.DeleteSense, callInfo)
	mock.lockDeleteSense.Unlock()
	return mock.DeleteSenseFunc(ctx, senseID)
}

// DeleteSenseCalls gets all the calls that were made to DeleteSense.
// Check the length with:
//
//	len(mockedcontentService.DeleteSenseCalls())
func (mock *contentServiceMock) DeleteSenseCalls() []struct {
	Ctx     context.Context
	SenseID uuid.UUID
} {
	var calls []struct {
		Ctx     context.Context
		SenseID uuid.UUID
	}
	mock.lockDeleteSense.RLock()
	calls = mock.calls.DeleteSense
	mock.lockDeleteSense.RUnlock()
	return calls
}

// DeleteTranslation calls DeleteTranslationFunc.
func (mock *contentServiceMock) DeleteTranslation(ctx context.Context, translationID uuid.UUID) error {
	if mock.DeleteTranslationFunc == nil {
		panic("contentServiceMock.DeleteTranslationFunc: method is nil but contentService.DeleteTranslation was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		TranslationID uuid.UUID
	}{
		Ctx:           ctx,
		TranslationID: translationID,
	}
	mock.lockDeleteTranslation.Lock()
	mock.calls.DeleteTranslation = append(mock.calls.DeleteTranslation, callInfo)
	mock.lockDeleteTranslation.Unlock()
	return mock.DeleteTranslationFunc(ctx, translationID)
}

// DeleteTranslationCalls gets all the calls that were made to DeleteTranslation.
// Check the length with:
//
//	len(mockedcontentService.DeleteTranslationCalls())
func (mock *contentServiceMock) DeleteTranslationCalls() []struct {
	Ctx           context.Context
	TranslationID uuid.UUID
} {
	var calls []struct {
		Ctx           context.Context
		TranslationID uuid.UUID
	}
	mock.lockDeleteTranslation.RLock()
	calls = mock.calls.DeleteTranslation
	mock.lockDeleteTranslation.RUnlock()
	return calls
}

// DeleteUserImage calls DeleteUserImageFunc.
func (mock *contentServiceMock) DeleteUserImage(ctx context.Context, imageID uuid.UUID) error {
	if mock.DeleteUserImageFunc == nil {
		panic("contentServiceMock.DeleteUserImageFunc: method is nil but contentService.DeleteUserImage was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ImageID uuid.UUID
	}{
		Ctx:     ctx,
		ImageID: imageID,
	}
	mock.lockDeleteUserImage.Lock()
	mock.calls.DeleteUserImage = append(mock.calls.DeleteUserImage, callInfo)
	mock.lockDeleteUserImage.Unlock()
	return mock.DeleteUserImageFunc(ctx, imageID)
}

// DeleteUserImageCalls gets all the calls that were made to DeleteUserImage.
// Check the length with:
//
//	len(mockedcontentService.DeleteUserImageCalls())
func (mock *contentServiceMock) DeleteUserImageCalls() []struct {
	Ctx     context.Context
	ImageID uuid.UUID
} {
	var calls []struct {
		Ctx     context.Context
		ImageID uuid.UUID
	}
	mock.lockDeleteUserImage.RLock()
	calls = mock.calls.DeleteUserImage
	mock.lockDeleteUserImage.RUnlock()
	return calls
}

// ReorderExamples calls ReorderExamplesFunc.
func (mock *contentServiceMock) ReorderExamples(ctx context.Context, input content.ReorderExamplesInput) error {
	if mock.ReorderExamplesFunc == nil {
		panic("contentServiceMock.ReorderExamplesFunc: method is nil but contentService.ReorderExamples was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.ReorderExamplesInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockReorderExamples.Lock()
	mock.calls.ReorderExamples = append(mock.calls.ReorderExamples, callInfo)
	mock.lockReorderExamples.Unlock()
	return mock.ReorderExamplesFunc(ctx, input)
}

// ReorderExamplesCalls gets all the calls that were made to ReorderExamples.
// Check the length with:
//
//	len(mockedcontentService.ReorderExamplesCalls())
func (mock *contentServiceMock) ReorderExamplesCalls() []struct {
	Ctx   context.Context
	Input content.ReorderExamplesInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.ReorderExamplesInput
	}
	mock.lockReorderExamples.RLock()
	calls = mock.calls.ReorderExamples
	mock.lockReorderExamples.RUnlock()
	return calls
}

// ReorderSenses calls ReorderSensesFunc.
func (mock *contentServiceMock) ReorderSenses(ctx context.Context, input content.ReorderSensesInput) error {
	if mock.ReorderSensesFunc == nil {
		panic("contentServiceMock.ReorderSensesFunc: method is nil but contentService.ReorderSenses was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.ReorderSensesInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockReorderSenses.Lock()
	mock.calls.ReorderSenses = append(mock.calls.ReorderSenses, callInfo)
	mock.lockReorderSenses.Unlock()
	return mock.ReorderSensesFunc(ctx, input)
}

// ReorderSensesCalls gets all the calls that were made to ReorderSenses.
// Check the length with:
//
//	len(mockedcontentService.ReorderSensesCalls())
func (mock *contentServiceMock) ReorderSensesCalls() []struct {
	Ctx   context.Context
	Input content.ReorderSensesInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.ReorderSensesInput
	}
	mock.lockReorderSenses.RLock()
	calls = mock.calls.ReorderSenses
	mock.lockReorderSenses.RUnlock()
	return calls
}

// ReorderTranslations calls ReorderTranslationsFunc.
func (mock *contentServiceMock) ReorderTranslations(ctx context.Context, input content.ReorderTranslationsInput) error {
	if mock.ReorderTranslationsFunc == nil {
		panic("contentServiceMock.ReorderTranslationsFunc: method is nil but contentService.ReorderTranslations was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.ReorderTranslationsInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockReorderTranslations.Lock()
	mock.calls.ReorderTranslations = append(mock.calls.ReorderTranslations, callInfo)
	mock.lockReorderTranslations.Unlock()
	return mock.ReorderTranslationsFunc(ctx, input)
}

// ReorderTranslationsCalls gets all the calls that were made to ReorderTranslations.
// Check the length with:
//
//	len(mockedcontentService.ReorderTranslationsCalls())
func (mock *contentServiceMock) ReorderTranslationsCalls() []struct {
	Ctx   context.Context
	Input content.ReorderTranslationsInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.ReorderTranslationsInput
	}
	mock.lockReorderTranslations.RLock()
	calls = mock.calls.ReorderTranslations
	mock.lockReorderTranslations.RUnlock()
	return calls
}

// UpdateExample calls UpdateExampleFunc.
func (mock *contentServiceMock) UpdateExample(ctx context.Context, input content.UpdateExampleInput) (*domain.Example, error) {
	if mock.UpdateExampleFunc == nil {
		panic("contentServiceMock.UpdateExampleFunc: method is nil but contentService.UpdateExample was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.UpdateExampleInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUpdateExample.Lock()
	mock.calls.UpdateExample = append(mock.calls.UpdateExample, callInfo)
	mock.lockUpdateExample.Unlock()
	return mock.UpdateExampleFunc(ctx, input)
}

// UpdateExampleCalls gets all the calls that were made to UpdateExample.
// Check the length with:
//
//	len(mockedcontentService.UpdateExampleCalls())
func (mock *contentServiceMock) UpdateExampleCalls() []struct {
	Ctx   context.Context
	Input content.UpdateExampleInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.UpdateExampleInput
	}
	mock.lockUpdateExample.RLock()
	calls = mock.calls.UpdateExample
	mock.lockUpdateExample.RUnlock()
	return calls
}

// UpdateSense calls UpdateSenseFunc.
func (mock *contentServiceMock) UpdateSense(ctx context.Context, input content.UpdateSenseInput) (*domain.Sense, error) {
	if mock.UpdateSenseFunc == nil {
		panic("contentServiceMock.UpdateSenseFunc: method is nil but contentService.UpdateSense was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.UpdateSenseInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUpdateSense.Lock()
	mock.calls.UpdateSense = append(mock.calls.UpdateSense, callInfo)
	mock.lockUpdateSense.Unlock()
	return mock.UpdateSenseFunc(ctx, input)
}

// UpdateSenseCalls gets all the calls that were made to UpdateSense.
// Check the length with:
//
//	len(mockedcontentService.UpdateSenseCalls())
func (mock *contentServiceMock) UpdateSenseCalls() []struct {
	Ctx   context.Context
	Input content.UpdateSenseInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.UpdateSenseInput
	}
	mock.lockUpdateSense.RLock()
	calls = mock.calls.UpdateSense
	mock.lockUpdateSense.RUnlock()
	return calls
}

// UpdateTranslation calls UpdateTranslationFunc.
func (mock *contentServiceMock) UpdateTranslation(ctx context.Context, input content.UpdateTranslationInput) (*domain.Translation, error) {
	if mock.UpdateTranslationFunc == nil {
		panic("contentServiceMock.UpdateTranslationFunc: method is nil but contentService.UpdateTranslation was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input content.UpdateTranslationInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUpdateTranslation.Lock()
	mock.calls.UpdateTranslation = append(mock.calls.UpdateTranslation, callInfo)
	mock.lockUpdateTranslation.Unlock()
	return mock.UpdateTranslationFunc(ctx, input)
}

// UpdateTranslationCalls gets all the calls that were made to UpdateTranslation.
// Check the length with:
//
//	len(mockedcontentService.UpdateTranslationCalls())
func (mock *contentServiceMock) UpdateTranslationCalls() []struct {
	Ctx   context.Context
	Input content.UpdateTranslationInput
} {
	var calls []struct {
		Ctx   context.Context
		Input content.UpdateTranslationInput
	}
	mock.lockUpdateTranslation.RLock()
	calls = mock.calls.UpdateTranslation
	mock.lockUpdateTranslation.RUnlock()
	return calls
}
