package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"github.com/heartmarshall/myenglish-backend/internal/transport/graphql/generated"
)

// CreateTopic is the resolver for the createTopic field.
func (r *mutationResolver) CreateTopic(ctx context.Context, input generated.CreateTopicInput) (*generated.CreateTopicPayload, error) {
	panic(fmt.Errorf("not implemented: CreateTopic - createTopic"))
}

// UpdateTopic is the resolver for the updateTopic field.
func (r *mutationResolver) UpdateTopic(ctx context.Context, input generated.UpdateTopicInput) (*generated.UpdateTopicPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateTopic - updateTopic"))
}

// DeleteTopic is the resolver for the deleteTopic field.
func (r *mutationResolver) DeleteTopic(ctx context.Context, id uuid.UUID) (*generated.DeleteTopicPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteTopic - deleteTopic"))
}

// LinkEntryToTopic is the resolver for the linkEntryToTopic field.
func (r *mutationResolver) LinkEntryToTopic(ctx context.Context, input generated.LinkEntryInput) (*generated.LinkEntryPayload, error) {
	panic(fmt.Errorf("not implemented: LinkEntryToTopic - linkEntryToTopic"))
}

// UnlinkEntryFromTopic is the resolver for the unlinkEntryFromTopic field.
func (r *mutationResolver) UnlinkEntryFromTopic(ctx context.Context, input generated.UnlinkEntryInput) (*generated.UnlinkEntryPayload, error) {
	panic(fmt.Errorf("not implemented: UnlinkEntryFromTopic - unlinkEntryFromTopic"))
}

// BatchLinkEntriesToTopic is the resolver for the batchLinkEntriesToTopic field.
func (r *mutationResolver) BatchLinkEntriesToTopic(ctx context.Context, input generated.BatchLinkEntriesInput) (*generated.BatchLinkPayload, error) {
	panic(fmt.Errorf("not implemented: BatchLinkEntriesToTopic - batchLinkEntriesToTopic"))
}

// CreateInboxItem is the resolver for the createInboxItem field.
func (r *mutationResolver) CreateInboxItem(ctx context.Context, input generated.CreateInboxItemInput) (*generated.CreateInboxItemPayload, error) {
	panic(fmt.Errorf("not implemented: CreateInboxItem - createInboxItem"))
}

// DeleteInboxItem is the resolver for the deleteInboxItem field.
func (r *mutationResolver) DeleteInboxItem(ctx context.Context, id uuid.UUID) (*generated.DeleteInboxItemPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteInboxItem - deleteInboxItem"))
}

// ClearInbox is the resolver for the clearInbox field.
func (r *mutationResolver) ClearInbox(ctx context.Context) (*generated.ClearInboxPayload, error) {
	panic(fmt.Errorf("not implemented: ClearInbox - clearInbox"))
}

// Topics is the resolver for the topics field.
func (r *queryResolver) Topics(ctx context.Context) ([]*domain.Topic, error) {
	panic(fmt.Errorf("not implemented: Topics - topics"))
}

// InboxItems is the resolver for the inboxItems field.
func (r *queryResolver) InboxItems(ctx context.Context, limit *int, offset *int) (*generated.InboxItemList, error) {
	panic(fmt.Errorf("not implemented: InboxItems - inboxItems"))
}

// InboxItem is the resolver for the inboxItem field.
func (r *queryResolver) InboxItem(ctx context.Context, id uuid.UUID) (*domain.InboxItem, error) {
	panic(fmt.Errorf("not implemented: InboxItem - inboxItem"))
}
