// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resolver

import (
	"context"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"github.com/heartmarshall/myenglish-backend/internal/service/topic"
	"sync"
)

// Ensure, that topicServiceMock does implement topicService.
// If this is not the case, regenerate this file with moq.
var _ topicService = &topicServiceMock{}

// topicServiceMock is a mock implementation of topicService.
//
//	func TestSomethingThatUsestopicService(t *testing.T) {
//
//		// make and configure a mocked topicService
//		mockedtopicService := &topicServiceMock{
//			BatchLinkEntriesFunc: func(ctx context.Context, input topic.BatchLinkEntriesInput) (*topic.BatchLinkResult, error) {
//				panic("mock out the BatchLinkEntries method")
//			},
//			CreateTopicFunc: func(ctx context.Context, input topic.CreateTopicInput) (*domain.Topic, error) {
//				panic("mock out the CreateTopic method")
//			},
//			DeleteTopicFunc: func(ctx context.Context, input topic.DeleteTopicInput) error {
//				panic("mock out the DeleteTopic method")
//			},
//			LinkEntryFunc: func(ctx context.Context, input topic.LinkEntryInput) error {
//				panic("mock out the LinkEntry method")
//			},
//			ListTopicsFunc: func(ctx context.Context) ([]*domain.Topic, error) {
//				panic("mock out the ListTopics method")
//			},
//			UnlinkEntryFunc: func(ctx context.Context, input topic.UnlinkEntryInput) error {
//				panic("mock out the UnlinkEntry method")
//			},
//			UpdateTopicFunc: func(ctx context.Context, input topic.UpdateTopicInput) (*domain.Topic, error) {
//				panic("mock out the UpdateTopic method")
//			},
//		}
//
//		// use mockedtopicService in code that requires topicService
//		// and then make assertions.
//
//	}
type topicServiceMock struct {
	// BatchLinkEntriesFunc mocks the BatchLinkEntries method.
	BatchLinkEntriesFunc func(ctx context.Context, input topic.BatchLinkEntriesInput) (*topic.BatchLinkResult, error)

	// CreateTopicFunc mocks the CreateTopic method.
	CreateTopicFunc func(ctx context.Context, input topic.CreateTopicInput) (*domain.Topic, error)

	// DeleteTopicFunc mocks the DeleteTopic method.
	DeleteTopicFunc func(ctx context.Context, input topic.DeleteTopicInput) error

	// LinkEntryFunc mocks the LinkEntry method.
	LinkEntryFunc func(ctx context.Context, input topic.LinkEntryInput) error

	// ListTopicsFunc mocks the ListTopics method.
	ListTopicsFunc func(ctx context.Context) ([]*domain.Topic, error)

	// UnlinkEntryFunc mocks the UnlinkEntry method.
	UnlinkEntryFunc func(ctx context.Context, input topic.UnlinkEntryInput) error

	// UpdateTopicFunc mocks the UpdateTopic method.
	UpdateTopicFunc func(ctx context.Context, input topic.UpdateTopicInput) (*domain.Topic, error)

	// calls tracks calls to the methods.
	calls struct {
		// BatchLinkEntries holds details about calls to the BatchLinkEntries method.
		BatchLinkEntries []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input topic.BatchLinkEntriesInput
		}
		// CreateTopic holds details about calls to the CreateTopic method.
		CreateTopic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input topic.CreateTopicInput
		}
		// DeleteTopic holds details about calls to the DeleteTopic method.
		DeleteTopic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input topic.DeleteTopicInput
		}
		// LinkEntry holds details about calls to the LinkEntry method.
		LinkEntry []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input topic.LinkEntryInput
		}
		// ListTopics holds details about calls to the ListTopics method.
		ListTopics []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UnlinkEntry holds details about calls to the UnlinkEntry method.
		UnlinkEntry []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input topic.UnlinkEntryInput
		}
		// UpdateTopic holds details about calls to the UpdateTopic method.
		UpdateTopic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input topic.UpdateTopicInput
		}
	}
	lockBatchLinkEntries sync.RWMutex
	lockCreateTopic      sync.RWMutex
	lockDeleteTopic      sync.RWMutex
	lockLinkEntry        sync.RWMutex
	lockListTopics       sync.RWMutex
	lockUnlinkEntry      sync.RWMutex
	lockUpdateTopic      sync.RWMutex
}

// BatchLinkEntries calls BatchLinkEntriesFunc.
func (mock *topicServiceMock) BatchLinkEntries(ctx context.Context, input topic.BatchLinkEntriesInput) (*topic.BatchLinkResult, error) {
	if mock.BatchLinkEntriesFunc == nil {
		panic("topicServiceMock.BatchLinkEntriesFunc: method is nil but topicService.BatchLinkEntries was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input topic.BatchLinkEntriesInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockBatchLinkEntries.Lock()
	mock.calls.BatchLinkEntries = append(mock.calls.BatchLinkEntries, callInfo)
	mock.lockBatchLinkEntries.Unlock()
	return mock.BatchLinkEntriesFunc(ctx, input)
}

// BatchLinkEntriesCalls gets all the calls that were made to BatchLinkEntries.
// Check the length with:
//
//	len(mockedtopicService.BatchLinkEntriesCalls())
func (mock *topicServiceMock) BatchLinkEntriesCalls() []struct {
	Ctx   context.Context
	Input topic.BatchLinkEntriesInput
} {
	var calls []struct {
		Ctx   context.Context
		Input topic.BatchLinkEntriesInput
	}
	mock.lockBatchLinkEntries.RLock()
	calls = mock.calls.BatchLinkEntries
	mock.lockBatchLinkEntries.RUnlock()
	return calls
}

// CreateTopic calls CreateTopicFunc.
func (mock *topicServiceMock) CreateTopic(ctx context.Context, input topic.CreateTopicInput) (*domain.Topic, error) {
	if mock.CreateTopicFunc == nil {
		panic("topicServiceMock.CreateTopicFunc: method is nil but topicService.CreateTopic was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input topic.CreateTopicInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateTopic.Lock()
	mock.calls.CreateTopic = append(mock.calls.CreateTopic, callInfo)
	mock.lockCreateTopic.Unlock()
	return mock.CreateTopicFunc(ctx, input)
}

// CreateTopicCalls gets all the calls that were made to CreateTopic.
// Check the length with:
//
//	len(mockedtopicService.CreateTopicCalls())
func (mock *topicServiceMock) CreateTopicCalls() []struct {
	Ctx   context.Context
	Input topic.CreateTopicInput
} {
	var calls []struct {
		Ctx   context.Context
		Input topic.CreateTopicInput
	}
	mock.lockCreateTopic.RLock()
	calls = mock.calls.CreateTopic
	mock.lockCreateTopic.RUnlock()
	return calls
}

// DeleteTopic calls DeleteTopicFunc.
func (mock *topicServiceMock) DeleteTopic(ctx context.Context, input topic.DeleteTopicInput) error {
	if mock.DeleteTopicFunc == nil {
		panic("topicServiceMock.DeleteTopicFunc: method is nil but topicService.DeleteTopic was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input topic.DeleteTopicInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockDeleteTopic.Lock()
	mock.calls.DeleteTopic = append(mock.calls.DeleteTopic, callInfo)
	mock.lockDeleteTopic.Unlock()
	return mock.DeleteTopicFunc(ctx, input)
}

// DeleteTopicCalls gets all the calls that were made to DeleteTopic.
// Check the length with:
//
//	len(mockedtopicService.DeleteTopicCalls())
func (mock *topicServiceMock) DeleteTopicCalls() []struct {
	Ctx   context.Context
	Input topic.DeleteTopicInput
} {
	var calls []struct {
		Ctx   context.Context
		Input topic.DeleteTopicInput
	}
	mock.lockDeleteTopic.RLock()
	calls = mock.calls.DeleteTopic
	mock.lockDeleteTopic.RUnlock()
	return calls
}

// LinkEntry calls LinkEntryFunc.
func (mock *topicServiceMock) LinkEntry(ctx context.Context, input topic.LinkEntryInput) error {
	if mock.LinkEntryFunc == nil {
		panic("topicServiceMock.LinkEntryFunc: method is nil but topicService.LinkEntry was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input topic.LinkEntryInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockLinkEntry.Lock()
	mock.calls.LinkEntry = append(mock.calls.LinkEntry, callInfo)
	mock.lockLinkEntry.Unlock()
	return mock.LinkEntryFunc(ctx, input)
}

// LinkEntryCalls gets all the calls that were made to LinkEntry.
// Check the length with:
//
//	len(mockedtopicService.LinkEntryCalls())
func (mock *topicServiceMock) LinkEntryCalls() []struct {
	Ctx   context.Context
	Input topic.LinkEntryInput
} {
	var calls []struct {
		Ctx   context.Context
		Input topic.LinkEntryInput
	}
	mock.lockLinkEntry.RLock()
	calls = mock.calls.LinkEntry
	mock.lockLinkEntry.RUnlock()
	return calls
}

// ListTopics calls ListTopicsFunc.
func (mock *topicServiceMock) ListTopics(ctx context.Context) ([]*domain.Topic, error) {
	if mock.ListTopicsFunc == nil {
		panic("topicServiceMock.ListTopicsFunc: method is nil but topicService.ListTopics was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListTopics.Lock()
	mock.calls.ListTopics = append(mock.calls.ListTopics, callInfo)
	mock.lockListTopics.Unlock()
	return mock.ListTopicsFunc(ctx)
}

// ListTopicsCalls gets all the calls that were made to ListTopics.
// Check the length with:
//
//	len(mockedtopicService.ListTopicsCalls())
func (mock *topicServiceMock) ListTopicsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListTopics.RLock()
	calls = mock.calls.ListTopics
	mock.lockListTopics.RUnlock()
	return calls
}

// UnlinkEntry calls UnlinkEntryFunc.
func (mock *topicServiceMock) UnlinkEntry(ctx context.Context, input topic.UnlinkEntryInput) error {
	if mock.UnlinkEntryFunc == nil {
		panic("topicServiceMock.UnlinkEntryFunc: method is nil but topicService.UnlinkEntry was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input topic.UnlinkEntryInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUnlinkEntry.Lock()
	mock.calls.UnlinkEntry = append(mock.calls.UnlinkEntry, callInfo)
	mock.lockUnlinkEntry.Unlock()
	return mock.UnlinkEntryFunc(ctx, input)
}

// UnlinkEntryCalls gets all the calls that were made to UnlinkEntry.
// Check the length with:
//
//	len(mockedtopicService.UnlinkEntryCalls())
func (mock *topicServiceMock) UnlinkEntryCalls() []struct {
	Ctx   context.Context
	Input topic.UnlinkEntryInput
} {
	var calls []struct {
		Ctx   context.Context
		Input topic.UnlinkEntryInput
	}
	mock.lockUnlinkEntry.RLock()
	calls = mock.calls.UnlinkEntry
	mock.lockUnlinkEntry.RUnlock()
	return calls
}

// UpdateTopic calls UpdateTopicFunc.
func (mock *topicServiceMock) UpdateTopic(ctx context.Context, input topic.UpdateTopicInput) (*domain.Topic, error) {
	if mock.UpdateTopicFunc == nil {
		panic("topicServiceMock.UpdateTopicFunc: method is nil but topicService.UpdateTopic was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input topic.UpdateTopicInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUpdateTopic.Lock()
	mock.calls.UpdateTopic = append(mock.calls.UpdateTopic, callInfo)
	mock.lockUpdateTopic.Unlock()
	return mock.UpdateTopicFunc(ctx, input)
}

// UpdateTopicCalls gets all the calls that were made to UpdateTopic.
// Check the length with:
//
//	len(mockedtopicService.UpdateTopicCalls())
func (mock *topicServiceMock) UpdateTopicCalls() []struct {
	Ctx   context.Context
	Input topic.UpdateTopicInput
} {
	var calls []struct {
		Ctx   context.Context
		Input topic.UpdateTopicInput
	}
	mock.lockUpdateTopic.RLock()
	calls = mock.calls.UpdateTopic
	mock.lockUpdateTopic.RUnlock()
	return calls
}
