// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resolver

import (
	"context"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"github.com/heartmarshall/myenglish-backend/internal/service/user"
	"sync"
)

// Ensure, that userServiceMock does implement userService.
// If this is not the case, regenerate this file with moq.
var _ userService = &userServiceMock{}

// userServiceMock is a mock implementation of userService.
//
//	func TestSomethingThatUsesuserService(t *testing.T) {
//
//		// make and configure a mocked userService
//		mockeduserService := &userServiceMock{
//			GetProfileFunc: func(ctx context.Context) (*domain.User, error) {
//				panic("mock out the GetProfile method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (*domain.UserSettings, error) {
//				panic("mock out the GetSettings method")
//			},
//			UpdateSettingsFunc: func(ctx context.Context, input user.UpdateSettingsInput) (*domain.UserSettings, error) {
//				panic("mock out the UpdateSettings method")
//			},
//		}
//
//		// use mockeduserService in code that requires userService
//		// and then make assertions.
//
//	}
type userServiceMock struct {
	// GetProfileFunc mocks the GetProfile method.
	GetProfileFunc func(ctx context.Context) (*domain.User, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (*domain.UserSettings, error)

	// UpdateSettingsFunc mocks the UpdateSettings method.
	UpdateSettingsFunc func(ctx context.Context, input user.UpdateSettingsInput) (*domain.UserSettings, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetProfile holds details about calls to the GetProfile method.
		GetProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateSettings holds details about calls to the UpdateSettings method.
		UpdateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input user.UpdateSettingsInput
		}
	}
	lockGetProfile     sync.RWMutex
	lockGetSettings    sync.RWMutex
	lockUpdateSettings sync.RWMutex
}

// GetProfile calls GetProfileFunc.
func (mock *userServiceMock) GetProfile(ctx context.Context) (*domain.User, error) {
	if mock.GetProfileFunc == nil {
		panic("userServiceMock.GetProfileFunc: method is nil but userService.GetProfile was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetProfile.Lock()
	mock.calls.GetProfile = append(mock.calls.GetProfile, callInfo)
	mock.lockGetProfile.Unlock()
	return mock.GetProfileFunc(ctx)
}

// GetProfileCalls gets all the calls that were made to GetProfile.
// Check the length with:
//
//	len(mockeduserService.GetProfileCalls())
func (mock *userServiceMock) GetProfileCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetProfile.RLock()
	calls = mock.calls.GetProfile
	mock.lockGetProfile.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *userServiceMock) GetSettings(ctx context.Context) (*domain.UserSettings, error) {
	if mock.GetSettingsFunc == nil {
		panic("userServiceMock.GetSettingsFunc: method is nil but userService.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockeduserService.GetSettingsCalls())
func (mock *userServiceMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// UpdateSettings calls UpdateSettingsFunc.
func (mock *userServiceMock) UpdateSettings(ctx context.Context, input user.UpdateSettingsInput) (*domain.UserSettings, error) {
	if mock.UpdateSettingsFunc == nil {
		panic("userServiceMock.UpdateSettingsFunc: method is nil but userService.UpdateSettings was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input user.UpdateSettingsInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUpdateSettings.Lock()
	mock.calls.UpdateSettings = append(mock.calls.UpdateSettings, callInfo)
	mock.lockUpdateSettings.Unlock()
	return mock.UpdateSettingsFunc(ctx, input)
}

// UpdateSettingsCalls gets all the calls that were made to UpdateSettings.
// Check the length with:
//
//	len(mockeduserService.UpdateSettingsCalls())
func (mock *userServiceMock) UpdateSettingsCalls() []struct {
	Ctx   context.Context
	Input user.UpdateSettingsInput
} {
	var calls []struct {
		Ctx   context.Context
		Input user.UpdateSettingsInput
	}
	mock.lockUpdateSettings.RLock()
	calls = mock.calls.UpdateSettings
	mock.lockUpdateSettings.RUnlock()
	return calls
}
