package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"github.com/heartmarshall/myenglish-backend/internal/service/user"
	"github.com/heartmarshall/myenglish-backend/internal/transport/graphql/generated"
	"github.com/heartmarshall/myenglish-backend/pkg/ctxutil"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input generated.UpdateSettingsInput) (*generated.UpdateSettingsPayload, error) {
	_, ok := ctxutil.UserIDFromCtx(ctx)
	if !ok {
		return nil, domain.ErrUnauthorized
	}

	serviceInput := user.UpdateSettingsInput{
		NewCardsPerDay:  input.NewCardsPerDay,
		ReviewsPerDay:   input.ReviewsPerDay,
		MaxIntervalDays: input.MaxIntervalDays,
		Timezone:        input.Timezone,
	}

	settings, err := r.user.UpdateSettings(ctx, serviceInput)
	if err != nil {
		return nil, err
	}

	return &generated.UpdateSettingsPayload{Settings: settings}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*domain.User, error) {
	_, ok := ctxutil.UserIDFromCtx(ctx)
	if !ok {
		return nil, domain.ErrUnauthorized
	}

	user, err := r.user.GetProfile(ctx)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// Settings is the resolver for the settings field.
func (r *userResolver) Settings(ctx context.Context, obj *domain.User) (*domain.UserSettings, error) {
	return r.user.GetSettings(ctx)
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
