// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resolver

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"github.com/heartmarshall/myenglish-backend/internal/service/user"
	"sync"
)

// Ensure, that userServiceMock does implement userService.
// If this is not the case, regenerate this file with moq.
var _ userService = &userServiceMock{}

// userServiceMock is a mock implementation of userService.
//
//	func TestSomethingThatUsesuserService(t *testing.T) {
//
//		// make and configure a mocked userService
//		mockeduserService := &userServiceMock{
//			GetProfileFunc: func(ctx context.Context) (*domain.User, error) {
//				panic("mock out the GetProfile method")
//			},
//			GetSettingsFunc: func(ctx context.Context) (*domain.UserSettings, error) {
//				panic("mock out the GetSettings method")
//			},
//			ListUsersFunc: func(ctx context.Context, limit int, offset int) ([]domain.User, int, error) {
//				panic("mock out the ListUsers method")
//			},
//			SetUserRoleFunc: func(ctx context.Context, targetUserID uuid.UUID, role domain.UserRole) (*domain.User, error) {
//				panic("mock out the SetUserRole method")
//			},
//			UpdateSettingsFunc: func(ctx context.Context, input user.UpdateSettingsInput) (*domain.UserSettings, error) {
//				panic("mock out the UpdateSettings method")
//			},
//		}
//
//		// use mockeduserService in code that requires userService
//		// and then make assertions.
//
//	}
type userServiceMock struct {
	// GetProfileFunc mocks the GetProfile method.
	GetProfileFunc func(ctx context.Context) (*domain.User, error)

	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context) (*domain.UserSettings, error)

	// ListUsersFunc mocks the ListUsers method.
	ListUsersFunc func(ctx context.Context, limit int, offset int) ([]domain.User, int, error)

	// SetUserRoleFunc mocks the SetUserRole method.
	SetUserRoleFunc func(ctx context.Context, targetUserID uuid.UUID, role domain.UserRole) (*domain.User, error)

	// UpdateSettingsFunc mocks the UpdateSettings method.
	UpdateSettingsFunc func(ctx context.Context, input user.UpdateSettingsInput) (*domain.UserSettings, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetProfile holds details about calls to the GetProfile method.
		GetProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListUsers holds details about calls to the ListUsers method.
		ListUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// SetUserRole holds details about calls to the SetUserRole method.
		SetUserRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TargetUserID is the targetUserID argument value.
			TargetUserID uuid.UUID
			// Role is the role argument value.
			Role domain.UserRole
		}
		// UpdateSettings holds details about calls to the UpdateSettings method.
		UpdateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input user.UpdateSettingsInput
		}
	}
	lockGetProfile     sync.RWMutex
	lockGetSettings    sync.RWMutex
	lockListUsers      sync.RWMutex
	lockSetUserRole    sync.RWMutex
	lockUpdateSettings sync.RWMutex
}

// GetProfile calls GetProfileFunc.
func (mock *userServiceMock) GetProfile(ctx context.Context) (*domain.User, error) {
	if mock.GetProfileFunc == nil {
		panic("userServiceMock.GetProfileFunc: method is nil but userService.GetProfile was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetProfile.Lock()
	mock.calls.GetProfile = append(mock.calls.GetProfile, callInfo)
	mock.lockGetProfile.Unlock()
	return mock.GetProfileFunc(ctx)
}

// GetProfileCalls gets all the calls that were made to GetProfile.
// Check the length with:
//
//	len(mockeduserService.GetProfileCalls())
func (mock *userServiceMock) GetProfileCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetProfile.RLock()
	calls = mock.calls.GetProfile
	mock.lockGetProfile.RUnlock()
	return calls
}

// GetSettings calls GetSettingsFunc.
func (mock *userServiceMock) GetSettings(ctx context.Context) (*domain.UserSettings, error) {
	if mock.GetSettingsFunc == nil {
		panic("userServiceMock.GetSettingsFunc: method is nil but userService.GetSettings was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockeduserService.GetSettingsCalls())
func (mock *userServiceMock) GetSettingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// ListUsers calls ListUsersFunc.
func (mock *userServiceMock) ListUsers(ctx context.Context, limit int, offset int) ([]domain.User, int, error) {
	if mock.ListUsersFunc == nil {
		panic("userServiceMock.ListUsersFunc: method is nil but userService.ListUsers was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListUsers.Lock()
	mock.calls.ListUsers = append(mock.calls.ListUsers, callInfo)
	mock.lockListUsers.Unlock()
	return mock.ListUsersFunc(ctx, limit, offset)
}

// ListUsersCalls gets all the calls that were made to ListUsers.
// Check the length with:
//
//	len(mockeduserService.ListUsersCalls())
func (mock *userServiceMock) ListUsersCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockListUsers.RLock()
	calls = mock.calls.ListUsers
	mock.lockListUsers.RUnlock()
	return calls
}

// SetUserRole calls SetUserRoleFunc.
func (mock *userServiceMock) SetUserRole(ctx context.Context, targetUserID uuid.UUID, role domain.UserRole) (*domain.User, error) {
	if mock.SetUserRoleFunc == nil {
		panic("userServiceMock.SetUserRoleFunc: method is nil but userService.SetUserRole was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		TargetUserID uuid.UUID
		Role         domain.UserRole
	}{
		Ctx:          ctx,
		TargetUserID: targetUserID,
		Role:         role,
	}
	mock.lockSetUserRole.Lock()
	mock.calls.SetUserRole = append(mock.calls.SetUserRole, callInfo)
	mock.lockSetUserRole.Unlock()
	return mock.SetUserRoleFunc(ctx, targetUserID, role)
}

// SetUserRoleCalls gets all the calls that were made to SetUserRole.
// Check the length with:
//
//	len(mockeduserService.SetUserRoleCalls())
func (mock *userServiceMock) SetUserRoleCalls() []struct {
	Ctx          context.Context
	TargetUserID uuid.UUID
	Role         domain.UserRole
} {
	var calls []struct {
		Ctx          context.Context
		TargetUserID uuid.UUID
		Role         domain.UserRole
	}
	mock.lockSetUserRole.RLock()
	calls = mock.calls.SetUserRole
	mock.lockSetUserRole.RUnlock()
	return calls
}

// UpdateSettings calls UpdateSettingsFunc.
func (mock *userServiceMock) UpdateSettings(ctx context.Context, input user.UpdateSettingsInput) (*domain.UserSettings, error) {
	if mock.UpdateSettingsFunc == nil {
		panic("userServiceMock.UpdateSettingsFunc: method is nil but userService.UpdateSettings was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input user.UpdateSettingsInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUpdateSettings.Lock()
	mock.calls.UpdateSettings = append(mock.calls.UpdateSettings, callInfo)
	mock.lockUpdateSettings.Unlock()
	return mock.UpdateSettingsFunc(ctx, input)
}

// UpdateSettingsCalls gets all the calls that were made to UpdateSettings.
// Check the length with:
//
//	len(mockeduserService.UpdateSettingsCalls())
func (mock *userServiceMock) UpdateSettingsCalls() []struct {
	Ctx   context.Context
	Input user.UpdateSettingsInput
} {
	var calls []struct {
		Ctx   context.Context
		Input user.UpdateSettingsInput
	}
	mock.lockUpdateSettings.RLock()
	calls = mock.calls.UpdateSettings
	mock.lockUpdateSettings.RUnlock()
	return calls
}
