package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"github.com/heartmarshall/myenglish-backend/internal/transport/graphql/generated"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input generated.UpdateSettingsInput) (*generated.UpdateSettingsPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateSettings - updateSettings"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*domain.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// OauthProvider is the resolver for the oauthProvider field.
func (r *userResolver) OauthProvider(ctx context.Context, obj *domain.User) (string, error) {
	panic(fmt.Errorf("not implemented: OauthProvider - oauthProvider"))
}

// Settings is the resolver for the settings field.
func (r *userResolver) Settings(ctx context.Context, obj *domain.User) (*domain.UserSettings, error) {
	return r.user.GetSettings(ctx)
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
