// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, description, created_at, updated_at
`

type CreateTopicParams struct {
	UserID      uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.UserID, arg.Name, arg.Description)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :execrows
DELETE FROM topics
WHERE id = $1 AND user_id = $2
`

type DeleteTopicParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTopic(ctx context.Context, arg DeleteTopicParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTopic, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEntryIDsByTopicID = `-- name: GetEntryIDsByTopicID :many
SELECT entry_id FROM entry_topics
WHERE topic_id = $1
`

func (q *Queries) GetEntryIDsByTopicID(ctx context.Context, topicID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getEntryIDsByTopicID, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var entry_id uuid.UUID
		if err := rows.Scan(&entry_id); err != nil {
			return nil, err
		}
		items = append(items, entry_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByID = `-- name: GetTopicByID :one

SELECT id, user_id, name, description, created_at, updated_at
FROM topics
WHERE id = $1 AND user_id = $2
`

type GetTopicByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// ---------------------------------------------------------------------------
// topics
// ---------------------------------------------------------------------------
func (q *Queries) GetTopicByID(ctx context.Context, arg GetTopicByIDParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, arg.ID, arg.UserID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkEntry = `-- name: LinkEntry :exec

INSERT INTO entry_topics (entry_id, topic_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkEntryParams struct {
	EntryID uuid.UUID
	TopicID uuid.UUID
}

// ---------------------------------------------------------------------------
// entry_topics (M2M)
// ---------------------------------------------------------------------------
func (q *Queries) LinkEntry(ctx context.Context, arg LinkEntryParams) error {
	_, err := q.db.Exec(ctx, linkEntry, arg.EntryID, arg.TopicID)
	return err
}

const listTopicsByUser = `-- name: ListTopicsByUser :many
SELECT id, user_id, name, description, created_at, updated_at
FROM topics
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListTopicsByUser(ctx context.Context, userID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkEntry = `-- name: UnlinkEntry :exec
DELETE FROM entry_topics
WHERE entry_id = $1 AND topic_id = $2
`

type UnlinkEntryParams struct {
	EntryID uuid.UUID
	TopicID uuid.UUID
}

func (q *Queries) UnlinkEntry(ctx context.Context, arg UnlinkEntryParams) error {
	_, err := q.db.Exec(ctx, unlinkEntry, arg.EntryID, arg.TopicID)
	return err
}

const updateTopic = `-- name: UpdateTopic :execrows
UPDATE topics
SET name = $1, description = $2, updated_at = now()
WHERE id = $3 AND user_id = $4
`

type UpdateTopicParams struct {
	Name        string
	Description pgtype.Text
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTopic,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
