// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_methods.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getByOAuth = `-- name: GetByOAuth :one
SELECT id, user_id, method, provider_id, password_hash, created_at, updated_at
FROM auth_methods
WHERE method = $1 AND provider_id = $2
`

type GetByOAuthParams struct {
	Method     string
	ProviderID pgtype.Text
}

func (q *Queries) GetByOAuth(ctx context.Context, arg GetByOAuthParams) (AuthMethod, error) {
	row := q.db.QueryRow(ctx, getByOAuth, arg.Method, arg.ProviderID)
	var i AuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.ProviderID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByUserAndMethod = `-- name: GetByUserAndMethod :one
SELECT id, user_id, method, provider_id, password_hash, created_at, updated_at
FROM auth_methods
WHERE user_id = $1 AND method = $2
`

type GetByUserAndMethodParams struct {
	UserID uuid.UUID
	Method string
}

func (q *Queries) GetByUserAndMethod(ctx context.Context, arg GetByUserAndMethodParams) (AuthMethod, error) {
	row := q.db.QueryRow(ctx, getByUserAndMethod, arg.UserID, arg.Method)
	var i AuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.ProviderID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthMethod = `-- name: CreateAuthMethod :one
INSERT INTO auth_methods (user_id, method, provider_id, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, user_id, method, provider_id, password_hash, created_at, updated_at
`

type CreateAuthMethodParams struct {
	UserID       uuid.UUID
	Method       string
	ProviderID   pgtype.Text
	PasswordHash pgtype.Text
}

func (q *Queries) CreateAuthMethod(ctx context.Context, arg CreateAuthMethodParams) (AuthMethod, error) {
	row := q.db.QueryRow(ctx, createAuthMethod,
		arg.UserID,
		arg.Method,
		arg.ProviderID,
		arg.PasswordHash,
	)
	var i AuthMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Method,
		&i.ProviderID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByUser = `-- name: ListByUser :many
SELECT id, user_id, method, provider_id, password_hash, created_at, updated_at
FROM auth_methods
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListByUser(ctx context.Context, userID uuid.UUID) ([]AuthMethod, error) {
	rows, err := q.db.Query(ctx, listByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthMethod
	for rows.Next() {
		var i AuthMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Method,
			&i.ProviderID,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
