// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthMethod struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Method       string
	ProviderID   pgtype.Text
	PasswordHash pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
