// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, user_id, ref_entry_id, text, text_normalized, notes,
       created_at, updated_at, deleted_at
FROM entries
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetEntryByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetEntryByID(ctx context.Context, arg GetEntryByIDParams) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntryByID, arg.ID, arg.UserID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefEntryID,
		&i.Text,
		&i.TextNormalized,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
