// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that settingsRepoMock does implement settingsRepo.
// If this is not the case, regenerate this file with moq.
var _ settingsRepo = &settingsRepoMock{}

// settingsRepoMock is a mock implementation of settingsRepo.
//
//	func TestSomethingThatUsessettingsRepo(t *testing.T) {
//
//		// make and configure a mocked settingsRepo
//		mockedsettingsRepo := &settingsRepoMock{
//			GetSettingsFunc: func(ctx context.Context, userID uuid.UUID) (domain.UserSettings, error) {
//				panic("mock out the GetSettings method")
//			},
//			UpdateSettingsFunc: func(ctx context.Context, userID uuid.UUID, s domain.UserSettings) (domain.UserSettings, error) {
//				panic("mock out the UpdateSettings method")
//			},
//		}
//
//		// use mockedsettingsRepo in code that requires settingsRepo
//		// and then make assertions.
//
//	}
type settingsRepoMock struct {
	// GetSettingsFunc mocks the GetSettings method.
	GetSettingsFunc func(ctx context.Context, userID uuid.UUID) (domain.UserSettings, error)

	// UpdateSettingsFunc mocks the UpdateSettings method.
	UpdateSettingsFunc func(ctx context.Context, userID uuid.UUID, s domain.UserSettings) (domain.UserSettings, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetSettings holds details about calls to the GetSettings method.
		GetSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// UpdateSettings holds details about calls to the UpdateSettings method.
		UpdateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// S is the s argument value.
			S domain.UserSettings
		}
	}
	lockGetSettings    sync.RWMutex
	lockUpdateSettings sync.RWMutex
}

// GetSettings calls GetSettingsFunc.
func (mock *settingsRepoMock) GetSettings(ctx context.Context, userID uuid.UUID) (domain.UserSettings, error) {
	if mock.GetSettingsFunc == nil {
		panic("settingsRepoMock.GetSettingsFunc: method is nil but settingsRepo.GetSettings was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetSettings.Lock()
	mock.calls.GetSettings = append(mock.calls.GetSettings, callInfo)
	mock.lockGetSettings.Unlock()
	return mock.GetSettingsFunc(ctx, userID)
}

// GetSettingsCalls gets all the calls that were made to GetSettings.
// Check the length with:
//
//	len(mockedsettingsRepo.GetSettingsCalls())
func (mock *settingsRepoMock) GetSettingsCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetSettings.RLock()
	calls = mock.calls.GetSettings
	mock.lockGetSettings.RUnlock()
	return calls
}

// UpdateSettings calls UpdateSettingsFunc.
func (mock *settingsRepoMock) UpdateSettings(ctx context.Context, userID uuid.UUID, s domain.UserSettings) (domain.UserSettings, error) {
	if mock.UpdateSettingsFunc == nil {
		panic("settingsRepoMock.UpdateSettingsFunc: method is nil but settingsRepo.UpdateSettings was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		S      domain.UserSettings
	}{
		Ctx:    ctx,
		UserID: userID,
		S:      s,
	}
	mock.lockUpdateSettings.Lock()
	mock.calls.UpdateSettings = append(mock.calls.UpdateSettings, callInfo)
	mock.lockUpdateSettings.Unlock()
	return mock.UpdateSettingsFunc(ctx, userID, s)
}

// UpdateSettingsCalls gets all the calls that were made to UpdateSettings.
// Check the length with:
//
//	len(mockedsettingsRepo.UpdateSettingsCalls())
func (mock *settingsRepoMock) UpdateSettingsCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	S      domain.UserSettings
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		S      domain.UserSettings
	}
	mock.lockUpdateSettings.RLock()
	calls = mock.calls.UpdateSettings
	mock.lockUpdateSettings.RUnlock()
	return calls
}
