// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"sync"
)

// Ensure, that txManagerMock does implement txManager.
// If this is not the case, regenerate this file with moq.
var _ txManager = &txManagerMock{}

// txManagerMock is a mock implementation of txManager.
//
//	func TestSomethingThatUsestxManager(t *testing.T) {
//
//		// make and configure a mocked txManager
//		mockedtxManager := &txManagerMock{
//			RunInTxFunc: func(ctx context.Context, fn func(ctx context.Context) error) error {
//				panic("mock out the RunInTx method")
//			},
//		}
//
//		// use mockedtxManager in code that requires txManager
//		// and then make assertions.
//
//	}
type txManagerMock struct {
	// RunInTxFunc mocks the RunInTx method.
	RunInTxFunc func(ctx context.Context, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// RunInTx holds details about calls to the RunInTx method.
		RunInTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockRunInTx sync.RWMutex
}

// RunInTx calls RunInTxFunc.
func (mock *txManagerMock) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	if mock.RunInTxFunc == nil {
		panic("txManagerMock.RunInTxFunc: method is nil but txManager.RunInTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockRunInTx.Lock()
	mock.calls.RunInTx = append(mock.calls.RunInTx, callInfo)
	mock.lockRunInTx.Unlock()
	return mock.RunInTxFunc(ctx, fn)
}

// RunInTxCalls gets all the calls that were made to RunInTx.
// Check the length with:
//
//	len(mockedtxManager.RunInTxCalls())
func (mock *txManagerMock) RunInTxCalls() []struct {
	Ctx context.Context
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}
	mock.lockRunInTx.RLock()
	calls = mock.calls.RunInTx
	mock.lockRunInTx.RUnlock()
	return calls
}
