// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that userRepoMock does implement userRepo.
// If this is not the case, regenerate this file with moq.
var _ userRepo = &userRepoMock{}

// userRepoMock is a mock implementation of userRepo.
//
//	func TestSomethingThatUsesuserRepo(t *testing.T) {
//
//		// make and configure a mocked userRepo
//		mockeduserRepo := &userRepoMock{
//			CountUsersFunc: func(ctx context.Context) (int, error) {
//				panic("mock out the CountUsers method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.User, error) {
//				panic("mock out the GetByID method")
//			},
//			ListUsersFunc: func(ctx context.Context, limit int, offset int) ([]domain.User, error) {
//				panic("mock out the ListUsers method")
//			},
//			UpdateFunc: func(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error) {
//				panic("mock out the Update method")
//			},
//			UpdateRoleFunc: func(ctx context.Context, id uuid.UUID, role string) (*domain.User, error) {
//				panic("mock out the UpdateRole method")
//			},
//		}
//
//		// use mockeduserRepo in code that requires userRepo
//		// and then make assertions.
//
//	}
type userRepoMock struct {
	// CountUsersFunc mocks the CountUsers method.
	CountUsersFunc func(ctx context.Context) (int, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.User, error)

	// ListUsersFunc mocks the ListUsers method.
	ListUsersFunc func(ctx context.Context, limit int, offset int) ([]domain.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error)

	// UpdateRoleFunc mocks the UpdateRole method.
	UpdateRoleFunc func(ctx context.Context, id uuid.UUID, role string) (*domain.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// CountUsers holds details about calls to the CountUsers method.
		CountUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// ListUsers holds details about calls to the ListUsers method.
		ListUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Name is the name argument value.
			Name *string
			// AvatarURL is the avatarURL argument value.
			AvatarURL *string
		}
		// UpdateRole holds details about calls to the UpdateRole method.
		UpdateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Role is the role argument value.
			Role string
		}
	}
	lockCountUsers sync.RWMutex
	lockGetByID    sync.RWMutex
	lockListUsers  sync.RWMutex
	lockUpdate     sync.RWMutex
	lockUpdateRole sync.RWMutex
}

// CountUsers calls CountUsersFunc.
func (mock *userRepoMock) CountUsers(ctx context.Context) (int, error) {
	if mock.CountUsersFunc == nil {
		panic("userRepoMock.CountUsersFunc: method is nil but userRepo.CountUsers was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountUsers.Lock()
	mock.calls.CountUsers = append(mock.calls.CountUsers, callInfo)
	mock.lockCountUsers.Unlock()
	return mock.CountUsersFunc(ctx)
}

// CountUsersCalls gets all the calls that were made to CountUsers.
// Check the length with:
//
//	len(mockeduserRepo.CountUsersCalls())
func (mock *userRepoMock) CountUsersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountUsers.RLock()
	calls = mock.calls.CountUsers
	mock.lockCountUsers.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *userRepoMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	if mock.GetByIDFunc == nil {
		panic("userRepoMock.GetByIDFunc: method is nil but userRepo.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockeduserRepo.GetByIDCalls())
func (mock *userRepoMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// ListUsers calls ListUsersFunc.
func (mock *userRepoMock) ListUsers(ctx context.Context, limit int, offset int) ([]domain.User, error) {
	if mock.ListUsersFunc == nil {
		panic("userRepoMock.ListUsersFunc: method is nil but userRepo.ListUsers was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListUsers.Lock()
	mock.calls.ListUsers = append(mock.calls.ListUsers, callInfo)
	mock.lockListUsers.Unlock()
	return mock.ListUsersFunc(ctx, limit, offset)
}

// ListUsersCalls gets all the calls that were made to ListUsers.
// Check the length with:
//
//	len(mockeduserRepo.ListUsersCalls())
func (mock *userRepoMock) ListUsersCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockListUsers.RLock()
	calls = mock.calls.ListUsers
	mock.lockListUsers.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *userRepoMock) Update(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error) {
	if mock.UpdateFunc == nil {
		panic("userRepoMock.UpdateFunc: method is nil but userRepo.Update was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        uuid.UUID
		Name      *string
		AvatarURL *string
	}{
		Ctx:       ctx,
		ID:        id,
		Name:      name,
		AvatarURL: avatarURL,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, name, avatarURL)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockeduserRepo.UpdateCalls())
func (mock *userRepoMock) UpdateCalls() []struct {
	Ctx       context.Context
	ID        uuid.UUID
	Name      *string
	AvatarURL *string
} {
	var calls []struct {
		Ctx       context.Context
		ID        uuid.UUID
		Name      *string
		AvatarURL *string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateRole calls UpdateRoleFunc.
func (mock *userRepoMock) UpdateRole(ctx context.Context, id uuid.UUID, role string) (*domain.User, error) {
	if mock.UpdateRoleFunc == nil {
		panic("userRepoMock.UpdateRoleFunc: method is nil but userRepo.UpdateRole was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		ID   uuid.UUID
		Role string
	}{
		Ctx:  ctx,
		ID:   id,
		Role: role,
	}
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = append(mock.calls.UpdateRole, callInfo)
	mock.lockUpdateRole.Unlock()
	return mock.UpdateRoleFunc(ctx, id, role)
}

// UpdateRoleCalls gets all the calls that were made to UpdateRole.
// Check the length with:
//
//	len(mockeduserRepo.UpdateRoleCalls())
func (mock *userRepoMock) UpdateRoleCalls() []struct {
	Ctx  context.Context
	ID   uuid.UUID
	Role string
} {
	var calls []struct {
		Ctx  context.Context
		ID   uuid.UUID
		Role string
	}
	mock.lockUpdateRole.RLock()
	calls = mock.calls.UpdateRole
	mock.lockUpdateRole.RUnlock()
	return calls
}
