// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInboxItemsByUser = `-- name: CountInboxItemsByUser :one
SELECT count(*) FROM inbox_items
WHERE user_id = $1
`

func (q *Queries) CountInboxItemsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInboxItemsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInboxItem = `-- name: CreateInboxItem :one
INSERT INTO inbox_items (id, user_id, text, context, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, text, context, created_at
`

type CreateInboxItemParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Text      string
	Context   pgtype.Text
	CreatedAt time.Time
}

func (q *Queries) CreateInboxItem(ctx context.Context, arg CreateInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRow(ctx, createInboxItem,
		arg.ID,
		arg.UserID,
		arg.Text,
		arg.Context,
		arg.CreatedAt,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllInboxItems = `-- name: DeleteAllInboxItems :exec
DELETE FROM inbox_items
WHERE user_id = $1
`

func (q *Queries) DeleteAllInboxItems(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllInboxItems, userID)
	return err
}

const deleteInboxItem = `-- name: DeleteInboxItem :execrows
DELETE FROM inbox_items
WHERE id = $1 AND user_id = $2
`

type DeleteInboxItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteInboxItem(ctx context.Context, arg DeleteInboxItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInboxItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInboxItemByID = `-- name: GetInboxItemByID :one

SELECT id, user_id, text, context, created_at
FROM inbox_items
WHERE id = $1 AND user_id = $2
`

type GetInboxItemByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// ---------------------------------------------------------------------------
// inbox_items
// ---------------------------------------------------------------------------
func (q *Queries) GetInboxItemByID(ctx context.Context, arg GetInboxItemByIDParams) (InboxItem, error) {
	row := q.db.QueryRow(ctx, getInboxItemByID, arg.ID, arg.UserID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const listInboxItemsByUser = `-- name: ListInboxItemsByUser :many
SELECT id, user_id, text, context, created_at
FROM inbox_items
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListInboxItemsByUserParams struct {
	UserID uuid.UUID
	Off    int32
	Lim    int32
}

func (q *Queries) ListInboxItemsByUser(ctx context.Context, arg ListInboxItemsByUserParams) ([]InboxItem, error) {
	rows, err := q.db.Query(ctx, listInboxItemsByUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
