// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditRecord = `-- name: CreateAuditRecord :one

INSERT INTO audit_log (id, user_id, entity_type, entity_id, action, changes, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, entity_type, entity_id, action, changes, created_at
`

type CreateAuditRecordParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	EntityType EntityType
	EntityID   pgtype.UUID
	Action     AuditAction
	Changes    []byte
	CreatedAt  time.Time
}

// ---------------------------------------------------------------------------
// audit_log
// ---------------------------------------------------------------------------
func (q *Queries) CreateAuditRecord(ctx context.Context, arg CreateAuditRecordParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditRecord,
		arg.ID,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Changes,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}

const getByEntity = `-- name: GetByEntity :many
SELECT id, user_id, entity_type, entity_id, action, changes, created_at
FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3::int
`

type GetByEntityParams struct {
	EntityType EntityType
	EntityID   pgtype.UUID
	Lim        int32
}

func (q *Queries) GetByEntity(ctx context.Context, arg GetByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getByEntity, arg.EntityType, arg.EntityID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByUser = `-- name: GetByUser :many
SELECT id, user_id, entity_type, entity_id, action, changes, created_at
FROM audit_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3::int OFFSET $2::int
`

type GetByUserParams struct {
	UserID uuid.UUID
	Off    int32
	Lim    int32
}

func (q *Queries) GetByUser(ctx context.Context, arg GetByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getByUser, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
