// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, username, name, avatar_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, username, name, avatar_url, role, created_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (user_id, new_cards_per_day, reviews_per_day, max_interval_days, desired_retention, timezone, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING user_id, new_cards_per_day, reviews_per_day, max_interval_days, desired_retention, timezone, updated_at
`

type CreateUserSettingsParams struct {
	UserID           uuid.UUID
	NewCardsPerDay   int32
	ReviewsPerDay    int32
	MaxIntervalDays  int32
	DesiredRetention float64
	Timezone         string
}

type CreateUserSettingsRow struct {
	UserID           uuid.UUID
	NewCardsPerDay   int32
	ReviewsPerDay    int32
	MaxIntervalDays  int32
	DesiredRetention float64
	Timezone         string
	UpdatedAt        time.Time
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (CreateUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, createUserSettings,
		arg.UserID,
		arg.NewCardsPerDay,
		arg.ReviewsPerDay,
		arg.MaxIntervalDays,
		arg.DesiredRetention,
		arg.Timezone,
	)
	var i CreateUserSettingsRow
	err := row.Scan(
		&i.UserID,
		&i.NewCardsPerDay,
		&i.ReviewsPerDay,
		&i.MaxIntervalDays,
		&i.DesiredRetention,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, name, avatar_url, role, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, name, avatar_url, role, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, name, avatar_url, role, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, new_cards_per_day, reviews_per_day, max_interval_days, desired_retention, timezone, updated_at
FROM user_settings
WHERE user_id = $1
`

type GetUserSettingsRow struct {
	UserID           uuid.UUID
	NewCardsPerDay   int32
	ReviewsPerDay    int32
	MaxIntervalDays  int32
	DesiredRetention float64
	Timezone         string
	UpdatedAt        time.Time
}

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (GetUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i GetUserSettingsRow
	err := row.Scan(
		&i.UserID,
		&i.NewCardsPerDay,
		&i.ReviewsPerDay,
		&i.MaxIntervalDays,
		&i.DesiredRetention,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, name, avatar_url, role, created_at, updated_at
FROM users
ORDER BY created_at
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, avatar_url = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, username, name, avatar_url, role, created_at, updated_at
`

type UpdateUserParams struct {
	ID        uuid.UUID
	Name      pgtype.Text
	AvatarUrl pgtype.Text
}

type UpdateUserRow struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.AvatarUrl)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, username, name, avatar_url, role, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

type UpdateUserRoleRow struct {
	ID        uuid.UUID
	Email     string
	Username  string
	Name      pgtype.Text
	AvatarUrl pgtype.Text
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET new_cards_per_day = $2, reviews_per_day = $3, max_interval_days = $4, desired_retention = $5, timezone = $6, updated_at = now()
WHERE user_id = $1
RETURNING user_id, new_cards_per_day, reviews_per_day, max_interval_days, desired_retention, timezone, updated_at
`

type UpdateUserSettingsParams struct {
	UserID           uuid.UUID
	NewCardsPerDay   int32
	ReviewsPerDay    int32
	MaxIntervalDays  int32
	DesiredRetention float64
	Timezone         string
}

type UpdateUserSettingsRow struct {
	UserID           uuid.UUID
	NewCardsPerDay   int32
	ReviewsPerDay    int32
	MaxIntervalDays  int32
	DesiredRetention float64
	Timezone         string
	UpdatedAt        time.Time
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UpdateUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.UserID,
		arg.NewCardsPerDay,
		arg.ReviewsPerDay,
		arg.MaxIntervalDays,
		arg.DesiredRetention,
		arg.Timezone,
	)
	var i UpdateUserSettingsRow
	err := row.Scan(
		&i.UserID,
		&i.NewCardsPerDay,
		&i.ReviewsPerDay,
		&i.MaxIntervalDays,
		&i.DesiredRetention,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}
