// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: senses.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countByEntry = `-- name: CountByEntry :one
SELECT count(*) FROM senses WHERE entry_id = $1
`

func (q *Queries) CountByEntry(ctx context.Context, entryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByEntry, entryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSenseCustom = `-- name: CreateSenseCustom :one
INSERT INTO senses (id, entry_id, definition, part_of_speech, cefr_level, source_slug, position, created_at)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE((SELECT MAX(position) FROM senses WHERE entry_id = $2), -1) + 1, $7)
RETURNING id, entry_id, ref_sense_id, definition, part_of_speech, cefr_level, source_slug, position, created_at
`

type CreateSenseCustomParams struct {
	ID           uuid.UUID
	EntryID      uuid.UUID
	Definition   pgtype.Text
	PartOfSpeech NullPartOfSpeech
	CefrLevel    pgtype.Text
	SourceSlug   string
	CreatedAt    time.Time
}

func (q *Queries) CreateSenseCustom(ctx context.Context, arg CreateSenseCustomParams) (Sense, error) {
	row := q.db.QueryRow(ctx, createSenseCustom,
		arg.ID,
		arg.EntryID,
		arg.Definition,
		arg.PartOfSpeech,
		arg.CefrLevel,
		arg.SourceSlug,
		arg.CreatedAt,
	)
	var i Sense
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RefSenseID,
		&i.Definition,
		&i.PartOfSpeech,
		&i.CefrLevel,
		&i.SourceSlug,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createSenseFromRef = `-- name: CreateSenseFromRef :one
INSERT INTO senses (id, entry_id, ref_sense_id, source_slug, position, created_at)
VALUES ($1, $2, $3, $4, COALESCE((SELECT MAX(position) FROM senses WHERE entry_id = $2), -1) + 1, $5)
RETURNING id, entry_id, ref_sense_id, definition, part_of_speech, cefr_level, source_slug, position, created_at
`

type CreateSenseFromRefParams struct {
	ID         uuid.UUID
	EntryID    uuid.UUID
	RefSenseID pgtype.UUID
	SourceSlug string
	CreatedAt  time.Time
}

func (q *Queries) CreateSenseFromRef(ctx context.Context, arg CreateSenseFromRefParams) (Sense, error) {
	row := q.db.QueryRow(ctx, createSenseFromRef,
		arg.ID,
		arg.EntryID,
		arg.RefSenseID,
		arg.SourceSlug,
		arg.CreatedAt,
	)
	var i Sense
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RefSenseID,
		&i.Definition,
		&i.PartOfSpeech,
		&i.CefrLevel,
		&i.SourceSlug,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSense = `-- name: DeleteSense :execrows
DELETE FROM senses WHERE id = $1
`

func (q *Queries) DeleteSense(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSense, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSense = `-- name: UpdateSense :one
UPDATE senses
SET definition = $2, part_of_speech = $3, cefr_level = $4
WHERE id = $1
RETURNING id, entry_id, ref_sense_id, definition, part_of_speech, cefr_level, source_slug, position, created_at
`

type UpdateSenseParams struct {
	ID           uuid.UUID
	Definition   pgtype.Text
	PartOfSpeech NullPartOfSpeech
	CefrLevel    pgtype.Text
}

func (q *Queries) UpdateSense(ctx context.Context, arg UpdateSenseParams) (Sense, error) {
	row := q.db.QueryRow(ctx, updateSense,
		arg.ID,
		arg.Definition,
		arg.PartOfSpeech,
		arg.CefrLevel,
	)
	var i Sense
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RefSenseID,
		&i.Definition,
		&i.PartOfSpeech,
		&i.CefrLevel,
		&i.SourceSlug,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateSensePosition = `-- name: UpdateSensePosition :exec
UPDATE senses SET position = $2 WHERE id = $1
`

type UpdateSensePositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateSensePosition(ctx context.Context, arg UpdateSensePositionParams) error {
	_, err := q.db.Exec(ctx, updateSensePosition, arg.ID, arg.Position)
	return err
}
