// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id, user_id, entry_id, status, ease_factor, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, entry_id, status, learning_step,
          next_review_at, interval_days, ease_factor, created_at, updated_at
`

type CreateCardParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	EntryID    uuid.UUID
	Status     LearningStatus
	EaseFactor float64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.UserID,
		arg.EntryID,
		arg.Status,
		arg.EaseFactor,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryID,
		&i.Status,
		&i.LearningStep,
		&i.NextReviewAt,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :execrows
DELETE FROM cards
WHERE id = $1 AND user_id = $2
`

type DeleteCardParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCard, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCardByEntryID = `-- name: GetCardByEntryID :one
SELECT id, user_id, entry_id, status, learning_step,
       next_review_at, interval_days, ease_factor, created_at, updated_at
FROM cards
WHERE entry_id = $1 AND user_id = $2
`

type GetCardByEntryIDParams struct {
	EntryID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetCardByEntryID(ctx context.Context, arg GetCardByEntryIDParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByEntryID, arg.EntryID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryID,
		&i.Status,
		&i.LearningStep,
		&i.NextReviewAt,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardByID = `-- name: GetCardByID :one

SELECT id, user_id, entry_id, status, learning_step,
       next_review_at, interval_days, ease_factor, created_at, updated_at
FROM cards
WHERE id = $1 AND user_id = $2
`

type GetCardByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// ---------------------------------------------------------------------------
// cards
// ---------------------------------------------------------------------------
func (q *Queries) GetCardByID(ctx context.Context, arg GetCardByIDParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, arg.ID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryID,
		&i.Status,
		&i.LearningStep,
		&i.NextReviewAt,
		&i.IntervalDays,
		&i.EaseFactor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCardSRS = `-- name: UpdateCardSRS :execrows
UPDATE cards
SET status = $1,
    next_review_at = $2,
    interval_days = $3,
    ease_factor = $4,
    learning_step = $5,
    updated_at = now()
WHERE id = $6 AND user_id = $7
`

type UpdateCardSRSParams struct {
	Status       LearningStatus
	NextReviewAt *time.Time
	IntervalDays int32
	EaseFactor   float64
	LearningStep int32
	ID           uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) UpdateCardSRS(ctx context.Context, arg UpdateCardSRSParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardSRS,
		arg.Status,
		arg.NextReviewAt,
		arg.IntervalDays,
		arg.EaseFactor,
		arg.LearningStep,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
