// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pronunciation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const linkPronunciation = `-- name: LinkPronunciation :exec
INSERT INTO entry_pronunciations (entry_id, ref_pronunciation_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkPronunciationParams struct {
	EntryID            uuid.UUID
	RefPronunciationID uuid.UUID
}

func (q *Queries) LinkPronunciation(ctx context.Context, arg LinkPronunciationParams) error {
	_, err := q.db.Exec(ctx, linkPronunciation, arg.EntryID, arg.RefPronunciationID)
	return err
}

const unlinkAllPronunciations = `-- name: UnlinkAllPronunciations :exec
DELETE FROM entry_pronunciations
WHERE entry_id = $1
`

func (q *Queries) UnlinkAllPronunciations(ctx context.Context, entryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkAllPronunciations, entryID)
	return err
}

const unlinkPronunciation = `-- name: UnlinkPronunciation :exec
DELETE FROM entry_pronunciations
WHERE entry_id = $1 AND ref_pronunciation_id = $2
`

type UnlinkPronunciationParams struct {
	EntryID            uuid.UUID
	RefPronunciationID uuid.UUID
}

func (q *Queries) UnlinkPronunciation(ctx context.Context, arg UnlinkPronunciationParams) error {
	_, err := q.db.Exec(ctx, unlinkPronunciation, arg.EntryID, arg.RefPronunciationID)
	return err
}
