// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that authMethodRepoMock does implement authMethodRepo.
// If this is not the case, regenerate this file with moq.
var _ authMethodRepo = &authMethodRepoMock{}

// authMethodRepoMock is a mock implementation of authMethodRepo.
type authMethodRepoMock struct {
	// GetByOAuthFunc mocks the GetByOAuth method.
	GetByOAuthFunc func(ctx context.Context, method domain.AuthMethodType, providerID string) (*domain.AuthMethod, error)

	// GetByUserAndMethodFunc mocks the GetByUserAndMethod method.
	GetByUserAndMethodFunc func(ctx context.Context, userID uuid.UUID, method domain.AuthMethodType) (*domain.AuthMethod, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, am *domain.AuthMethod) (*domain.AuthMethod, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByOAuth holds details about calls to the GetByOAuth method.
		GetByOAuth []struct {
			Ctx        context.Context
			Method     domain.AuthMethodType
			ProviderID string
		}
		// GetByUserAndMethod holds details about calls to the GetByUserAndMethod method.
		GetByUserAndMethod []struct {
			Ctx    context.Context
			UserID uuid.UUID
			Method domain.AuthMethodType
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			Ctx context.Context
			Am  *domain.AuthMethod
		}
	}
	lockGetByOAuth         sync.RWMutex
	lockGetByUserAndMethod sync.RWMutex
	lockCreate             sync.RWMutex
}

func (mock *authMethodRepoMock) GetByOAuth(ctx context.Context, method domain.AuthMethodType, providerID string) (*domain.AuthMethod, error) {
	if mock.GetByOAuthFunc == nil {
		panic("authMethodRepoMock.GetByOAuthFunc: method is nil but authMethodRepo.GetByOAuth was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Method     domain.AuthMethodType
		ProviderID string
	}{
		Ctx:        ctx,
		Method:     method,
		ProviderID: providerID,
	}
	mock.lockGetByOAuth.Lock()
	mock.calls.GetByOAuth = append(mock.calls.GetByOAuth, callInfo)
	mock.lockGetByOAuth.Unlock()
	return mock.GetByOAuthFunc(ctx, method, providerID)
}

func (mock *authMethodRepoMock) GetByOAuthCalls() []struct {
	Ctx        context.Context
	Method     domain.AuthMethodType
	ProviderID string
} {
	mock.lockGetByOAuth.RLock()
	calls := mock.calls.GetByOAuth
	mock.lockGetByOAuth.RUnlock()
	return calls
}

func (mock *authMethodRepoMock) GetByUserAndMethod(ctx context.Context, userID uuid.UUID, method domain.AuthMethodType) (*domain.AuthMethod, error) {
	if mock.GetByUserAndMethodFunc == nil {
		panic("authMethodRepoMock.GetByUserAndMethodFunc: method is nil but authMethodRepo.GetByUserAndMethod was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		Method domain.AuthMethodType
	}{
		Ctx:    ctx,
		UserID: userID,
		Method: method,
	}
	mock.lockGetByUserAndMethod.Lock()
	mock.calls.GetByUserAndMethod = append(mock.calls.GetByUserAndMethod, callInfo)
	mock.lockGetByUserAndMethod.Unlock()
	return mock.GetByUserAndMethodFunc(ctx, userID, method)
}

func (mock *authMethodRepoMock) GetByUserAndMethodCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	Method domain.AuthMethodType
} {
	mock.lockGetByUserAndMethod.RLock()
	calls := mock.calls.GetByUserAndMethod
	mock.lockGetByUserAndMethod.RUnlock()
	return calls
}

func (mock *authMethodRepoMock) Create(ctx context.Context, am *domain.AuthMethod) (*domain.AuthMethod, error) {
	if mock.CreateFunc == nil {
		panic("authMethodRepoMock.CreateFunc: method is nil but authMethodRepo.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Am  *domain.AuthMethod
	}{
		Ctx: ctx,
		Am:  am,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, am)
}

func (mock *authMethodRepoMock) CreateCalls() []struct {
	Ctx context.Context
	Am  *domain.AuthMethod
} {
	mock.lockCreate.RLock()
	calls := mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
