// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"github.com/google/uuid"
	"sync"
)

// Ensure, that jwtManagerMock does implement jwtManager.
// If this is not the case, regenerate this file with moq.
var _ jwtManager = &jwtManagerMock{}

// jwtManagerMock is a mock implementation of jwtManager.
//
//	func TestSomethingThatUsesjwtManager(t *testing.T) {
//
//		// make and configure a mocked jwtManager
//		mockedjwtManager := &jwtManagerMock{
//			GenerateAccessTokenFunc: func(userID uuid.UUID, role string) (string, error) {
//				panic("mock out the GenerateAccessToken method")
//			},
//			GenerateRefreshTokenFunc: func() (string, string, error) {
//				panic("mock out the GenerateRefreshToken method")
//			},
//			ValidateAccessTokenFunc: func(token string) (uuid.UUID, string, error) {
//				panic("mock out the ValidateAccessToken method")
//			},
//		}
//
//		// use mockedjwtManager in code that requires jwtManager
//		// and then make assertions.
//
//	}
type jwtManagerMock struct {
	// GenerateAccessTokenFunc mocks the GenerateAccessToken method.
	GenerateAccessTokenFunc func(userID uuid.UUID, role string) (string, error)

	// GenerateRefreshTokenFunc mocks the GenerateRefreshToken method.
	GenerateRefreshTokenFunc func() (string, string, error)

	// ValidateAccessTokenFunc mocks the ValidateAccessToken method.
	ValidateAccessTokenFunc func(token string) (uuid.UUID, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateAccessToken holds details about calls to the GenerateAccessToken method.
		GenerateAccessToken []struct {
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Role is the role argument value.
			Role string
		}
		// GenerateRefreshToken holds details about calls to the GenerateRefreshToken method.
		GenerateRefreshToken []struct {
		}
		// ValidateAccessToken holds details about calls to the ValidateAccessToken method.
		ValidateAccessToken []struct {
			// Token is the token argument value.
			Token string
		}
	}
	lockGenerateAccessToken  sync.RWMutex
	lockGenerateRefreshToken sync.RWMutex
	lockValidateAccessToken  sync.RWMutex
}

// GenerateAccessToken calls GenerateAccessTokenFunc.
func (mock *jwtManagerMock) GenerateAccessToken(userID uuid.UUID, role string) (string, error) {
	if mock.GenerateAccessTokenFunc == nil {
		panic("jwtManagerMock.GenerateAccessTokenFunc: method is nil but jwtManager.GenerateAccessToken was just called")
	}
	callInfo := struct {
		UserID uuid.UUID
		Role   string
	}{
		UserID: userID,
		Role:   role,
	}
	mock.lockGenerateAccessToken.Lock()
	mock.calls.GenerateAccessToken = append(mock.calls.GenerateAccessToken, callInfo)
	mock.lockGenerateAccessToken.Unlock()
	return mock.GenerateAccessTokenFunc(userID, role)
}

// GenerateAccessTokenCalls gets all the calls that were made to GenerateAccessToken.
// Check the length with:
//
//	len(mockedjwtManager.GenerateAccessTokenCalls())
func (mock *jwtManagerMock) GenerateAccessTokenCalls() []struct {
	UserID uuid.UUID
	Role   string
} {
	var calls []struct {
		UserID uuid.UUID
		Role   string
	}
	mock.lockGenerateAccessToken.RLock()
	calls = mock.calls.GenerateAccessToken
	mock.lockGenerateAccessToken.RUnlock()
	return calls
}

// GenerateRefreshToken calls GenerateRefreshTokenFunc.
func (mock *jwtManagerMock) GenerateRefreshToken() (string, string, error) {
	if mock.GenerateRefreshTokenFunc == nil {
		panic("jwtManagerMock.GenerateRefreshTokenFunc: method is nil but jwtManager.GenerateRefreshToken was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGenerateRefreshToken.Lock()
	mock.calls.GenerateRefreshToken = append(mock.calls.GenerateRefreshToken, callInfo)
	mock.lockGenerateRefreshToken.Unlock()
	return mock.GenerateRefreshTokenFunc()
}

// GenerateRefreshTokenCalls gets all the calls that were made to GenerateRefreshToken.
// Check the length with:
//
//	len(mockedjwtManager.GenerateRefreshTokenCalls())
func (mock *jwtManagerMock) GenerateRefreshTokenCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGenerateRefreshToken.RLock()
	calls = mock.calls.GenerateRefreshToken
	mock.lockGenerateRefreshToken.RUnlock()
	return calls
}

// ValidateAccessToken calls ValidateAccessTokenFunc.
func (mock *jwtManagerMock) ValidateAccessToken(token string) (uuid.UUID, string, error) {
	if mock.ValidateAccessTokenFunc == nil {
		panic("jwtManagerMock.ValidateAccessTokenFunc: method is nil but jwtManager.ValidateAccessToken was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockValidateAccessToken.Lock()
	mock.calls.ValidateAccessToken = append(mock.calls.ValidateAccessToken, callInfo)
	mock.lockValidateAccessToken.Unlock()
	return mock.ValidateAccessTokenFunc(token)
}

// ValidateAccessTokenCalls gets all the calls that were made to ValidateAccessToken.
// Check the length with:
//
//	len(mockedjwtManager.ValidateAccessTokenCalls())
func (mock *jwtManagerMock) ValidateAccessTokenCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockValidateAccessToken.RLock()
	calls = mock.calls.ValidateAccessToken
	mock.lockValidateAccessToken.RUnlock()
	return calls
}
