// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that settingsRepoMock does implement settingsRepo.
// If this is not the case, regenerate this file with moq.
var _ settingsRepo = &settingsRepoMock{}

// settingsRepoMock is a mock implementation of settingsRepo.
//
//	func TestSomethingThatUsessettingsRepo(t *testing.T) {
//
//		// make and configure a mocked settingsRepo
//		mockedsettingsRepo := &settingsRepoMock{
//			CreateSettingsFunc: func(ctx context.Context, settings *domain.UserSettings) error {
//				panic("mock out the CreateSettings method")
//			},
//		}
//
//		// use mockedsettingsRepo in code that requires settingsRepo
//		// and then make assertions.
//
//	}
type settingsRepoMock struct {
	// CreateSettingsFunc mocks the CreateSettings method.
	CreateSettingsFunc func(ctx context.Context, settings *domain.UserSettings) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateSettings holds details about calls to the CreateSettings method.
		CreateSettings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Settings is the settings argument value.
			Settings *domain.UserSettings
		}
	}
	lockCreateSettings sync.RWMutex
}

// CreateSettings calls CreateSettingsFunc.
func (mock *settingsRepoMock) CreateSettings(ctx context.Context, settings *domain.UserSettings) error {
	if mock.CreateSettingsFunc == nil {
		panic("settingsRepoMock.CreateSettingsFunc: method is nil but settingsRepo.CreateSettings was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Settings *domain.UserSettings
	}{
		Ctx:      ctx,
		Settings: settings,
	}
	mock.lockCreateSettings.Lock()
	mock.calls.CreateSettings = append(mock.calls.CreateSettings, callInfo)
	mock.lockCreateSettings.Unlock()
	return mock.CreateSettingsFunc(ctx, settings)
}

// CreateSettingsCalls gets all the calls that were made to CreateSettings.
// Check the length with:
//
//	len(mockedsettingsRepo.CreateSettingsCalls())
func (mock *settingsRepoMock) CreateSettingsCalls() []struct {
	Ctx      context.Context
	Settings *domain.UserSettings
} {
	var calls []struct {
		Ctx      context.Context
		Settings *domain.UserSettings
	}
	mock.lockCreateSettings.RLock()
	calls = mock.calls.CreateSettings
	mock.lockCreateSettings.RUnlock()
	return calls
}
