// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that tokenRepoMock does implement tokenRepo.
// If this is not the case, regenerate this file with moq.
var _ tokenRepo = &tokenRepoMock{}

// tokenRepoMock is a mock implementation of tokenRepo.
//
//	func TestSomethingThatUsestokenRepo(t *testing.T) {
//
//		// make and configure a mocked tokenRepo
//		mockedtokenRepo := &tokenRepoMock{
//			CreateFunc: func(ctx context.Context, token *domain.RefreshToken) error {
//				panic("mock out the Create method")
//			},
//			DeleteExpiredFunc: func(ctx context.Context) (int, error) {
//				panic("mock out the DeleteExpired method")
//			},
//			GetByHashFunc: func(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
//				panic("mock out the GetByHash method")
//			},
//			RevokeAllByUserFunc: func(ctx context.Context, userID uuid.UUID) error {
//				panic("mock out the RevokeAllByUser method")
//			},
//			RevokeByIDFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the RevokeByID method")
//			},
//		}
//
//		// use mockedtokenRepo in code that requires tokenRepo
//		// and then make assertions.
//
//	}
type tokenRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, token *domain.RefreshToken) error

	// DeleteExpiredFunc mocks the DeleteExpired method.
	DeleteExpiredFunc func(ctx context.Context) (int, error)

	// GetByHashFunc mocks the GetByHash method.
	GetByHashFunc func(ctx context.Context, tokenHash string) (*domain.RefreshToken, error)

	// RevokeAllByUserFunc mocks the RevokeAllByUser method.
	RevokeAllByUserFunc func(ctx context.Context, userID uuid.UUID) error

	// RevokeByIDFunc mocks the RevokeByID method.
	RevokeByIDFunc func(ctx context.Context, id uuid.UUID) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token *domain.RefreshToken
		}
		// DeleteExpired holds details about calls to the DeleteExpired method.
		DeleteExpired []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetByHash holds details about calls to the GetByHash method.
		GetByHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TokenHash is the tokenHash argument value.
			TokenHash string
		}
		// RevokeAllByUser holds details about calls to the RevokeAllByUser method.
		RevokeAllByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// RevokeByID holds details about calls to the RevokeByID method.
		RevokeByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockCreate          sync.RWMutex
	lockDeleteExpired   sync.RWMutex
	lockGetByHash       sync.RWMutex
	lockRevokeAllByUser sync.RWMutex
	lockRevokeByID      sync.RWMutex
}

// Create calls CreateFunc.
func (mock *tokenRepoMock) Create(ctx context.Context, token *domain.RefreshToken) error {
	if mock.CreateFunc == nil {
		panic("tokenRepoMock.CreateFunc: method is nil but tokenRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token *domain.RefreshToken
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, token)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedtokenRepo.CreateCalls())
func (mock *tokenRepoMock) CreateCalls() []struct {
	Ctx   context.Context
	Token *domain.RefreshToken
} {
	var calls []struct {
		Ctx   context.Context
		Token *domain.RefreshToken
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteExpired calls DeleteExpiredFunc.
func (mock *tokenRepoMock) DeleteExpired(ctx context.Context) (int, error) {
	if mock.DeleteExpiredFunc == nil {
		panic("tokenRepoMock.DeleteExpiredFunc: method is nil but tokenRepo.DeleteExpired was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDeleteExpired.Lock()
	mock.calls.DeleteExpired = append(mock.calls.DeleteExpired, callInfo)
	mock.lockDeleteExpired.Unlock()
	return mock.DeleteExpiredFunc(ctx)
}

// DeleteExpiredCalls gets all the calls that were made to DeleteExpired.
// Check the length with:
//
//	len(mockedtokenRepo.DeleteExpiredCalls())
func (mock *tokenRepoMock) DeleteExpiredCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDeleteExpired.RLock()
	calls = mock.calls.DeleteExpired
	mock.lockDeleteExpired.RUnlock()
	return calls
}

// GetByHash calls GetByHashFunc.
func (mock *tokenRepoMock) GetByHash(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	if mock.GetByHashFunc == nil {
		panic("tokenRepoMock.GetByHashFunc: method is nil but tokenRepo.GetByHash was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		TokenHash string
	}{
		Ctx:       ctx,
		TokenHash: tokenHash,
	}
	mock.lockGetByHash.Lock()
	mock.calls.GetByHash = append(mock.calls.GetByHash, callInfo)
	mock.lockGetByHash.Unlock()
	return mock.GetByHashFunc(ctx, tokenHash)
}

// GetByHashCalls gets all the calls that were made to GetByHash.
// Check the length with:
//
//	len(mockedtokenRepo.GetByHashCalls())
func (mock *tokenRepoMock) GetByHashCalls() []struct {
	Ctx       context.Context
	TokenHash string
} {
	var calls []struct {
		Ctx       context.Context
		TokenHash string
	}
	mock.lockGetByHash.RLock()
	calls = mock.calls.GetByHash
	mock.lockGetByHash.RUnlock()
	return calls
}

// RevokeAllByUser calls RevokeAllByUserFunc.
func (mock *tokenRepoMock) RevokeAllByUser(ctx context.Context, userID uuid.UUID) error {
	if mock.RevokeAllByUserFunc == nil {
		panic("tokenRepoMock.RevokeAllByUserFunc: method is nil but tokenRepo.RevokeAllByUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockRevokeAllByUser.Lock()
	mock.calls.RevokeAllByUser = append(mock.calls.RevokeAllByUser, callInfo)
	mock.lockRevokeAllByUser.Unlock()
	return mock.RevokeAllByUserFunc(ctx, userID)
}

// RevokeAllByUserCalls gets all the calls that were made to RevokeAllByUser.
// Check the length with:
//
//	len(mockedtokenRepo.RevokeAllByUserCalls())
func (mock *tokenRepoMock) RevokeAllByUserCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockRevokeAllByUser.RLock()
	calls = mock.calls.RevokeAllByUser
	mock.lockRevokeAllByUser.RUnlock()
	return calls
}

// RevokeByID calls RevokeByIDFunc.
func (mock *tokenRepoMock) RevokeByID(ctx context.Context, id uuid.UUID) error {
	if mock.RevokeByIDFunc == nil {
		panic("tokenRepoMock.RevokeByIDFunc: method is nil but tokenRepo.RevokeByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRevokeByID.Lock()
	mock.calls.RevokeByID = append(mock.calls.RevokeByID, callInfo)
	mock.lockRevokeByID.Unlock()
	return mock.RevokeByIDFunc(ctx, id)
}

// RevokeByIDCalls gets all the calls that were made to RevokeByID.
// Check the length with:
//
//	len(mockedtokenRepo.RevokeByIDCalls())
func (mock *tokenRepoMock) RevokeByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockRevokeByID.RLock()
	calls = mock.calls.RevokeByID
	mock.lockRevokeByID.RUnlock()
	return calls
}
