// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that userRepoMock does implement userRepo.
// If this is not the case, regenerate this file with moq.
var _ userRepo = &userRepoMock{}

// userRepoMock is a mock implementation of userRepo.
//
//	func TestSomethingThatUsesuserRepo(t *testing.T) {
//
//		// make and configure a mocked userRepo
//		mockeduserRepo := &userRepoMock{
//			CreateFunc: func(ctx context.Context, user *domain.User) (*domain.User, error) {
//				panic("mock out the Create method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*domain.User, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByOAuthFunc: func(ctx context.Context, provider domain.OAuthProvider, oauthID string) (*domain.User, error) {
//				panic("mock out the GetByOAuth method")
//			},
//			UpdateFunc: func(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockeduserRepo in code that requires userRepo
//		// and then make assertions.
//
//	}
type userRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *domain.User) (*domain.User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.User, error)

	// GetByOAuthFunc mocks the GetByOAuth method.
	GetByOAuthFunc func(ctx context.Context, provider domain.OAuthProvider, oauthID string) (*domain.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *domain.User
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByOAuth holds details about calls to the GetByOAuth method.
		GetByOAuth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Provider is the provider argument value.
			Provider domain.OAuthProvider
			// OauthID is the oauthID argument value.
			OauthID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Name is the name argument value.
			Name *string
			// AvatarURL is the avatarURL argument value.
			AvatarURL *string
		}
	}
	lockCreate     sync.RWMutex
	lockGetByID    sync.RWMutex
	lockGetByOAuth sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Create calls CreateFunc.
func (mock *userRepoMock) Create(ctx context.Context, user *domain.User) (*domain.User, error) {
	if mock.CreateFunc == nil {
		panic("userRepoMock.CreateFunc: method is nil but userRepo.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockeduserRepo.CreateCalls())
func (mock *userRepoMock) CreateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	var calls []struct {
		Ctx  context.Context
		User *domain.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *userRepoMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	if mock.GetByIDFunc == nil {
		panic("userRepoMock.GetByIDFunc: method is nil but userRepo.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockeduserRepo.GetByIDCalls())
func (mock *userRepoMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByOAuth calls GetByOAuthFunc.
func (mock *userRepoMock) GetByOAuth(ctx context.Context, provider domain.OAuthProvider, oauthID string) (*domain.User, error) {
	if mock.GetByOAuthFunc == nil {
		panic("userRepoMock.GetByOAuthFunc: method is nil but userRepo.GetByOAuth was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Provider domain.OAuthProvider
		OauthID  string
	}{
		Ctx:      ctx,
		Provider: provider,
		OauthID:  oauthID,
	}
	mock.lockGetByOAuth.Lock()
	mock.calls.GetByOAuth = append(mock.calls.GetByOAuth, callInfo)
	mock.lockGetByOAuth.Unlock()
	return mock.GetByOAuthFunc(ctx, provider, oauthID)
}

// GetByOAuthCalls gets all the calls that were made to GetByOAuth.
// Check the length with:
//
//	len(mockeduserRepo.GetByOAuthCalls())
func (mock *userRepoMock) GetByOAuthCalls() []struct {
	Ctx      context.Context
	Provider domain.OAuthProvider
	OauthID  string
} {
	var calls []struct {
		Ctx      context.Context
		Provider domain.OAuthProvider
		OauthID  string
	}
	mock.lockGetByOAuth.RLock()
	calls = mock.calls.GetByOAuth
	mock.lockGetByOAuth.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *userRepoMock) Update(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error) {
	if mock.UpdateFunc == nil {
		panic("userRepoMock.UpdateFunc: method is nil but userRepo.Update was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        uuid.UUID
		Name      *string
		AvatarURL *string
	}{
		Ctx:       ctx,
		ID:        id,
		Name:      name,
		AvatarURL: avatarURL,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, name, avatarURL)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockeduserRepo.UpdateCalls())
func (mock *userRepoMock) UpdateCalls() []struct {
	Ctx       context.Context
	ID        uuid.UUID
	Name      *string
	AvatarURL *string
} {
	var calls []struct {
		Ctx       context.Context
		ID        uuid.UUID
		Name      *string
		AvatarURL *string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
