// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"github.com/google/uuid"
	"github.com/heartmarshall/myenglish-backend/internal/domain"
	"sync"
)

// Ensure, that userRepoMock does implement userRepo.
// If this is not the case, regenerate this file with moq.
var _ userRepo = &userRepoMock{}

// userRepoMock is a mock implementation of userRepo.
type userRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *domain.User) (*domain.User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*domain.User, error)

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(ctx context.Context, email string) (*domain.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			Ctx  context.Context
			User *domain.User
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			Ctx context.Context
			ID  uuid.UUID
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			Ctx   context.Context
			Email string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			Ctx       context.Context
			ID        uuid.UUID
			Name      *string
			AvatarURL *string
		}
	}
	lockCreate     sync.RWMutex
	lockGetByID    sync.RWMutex
	lockGetByEmail sync.RWMutex
	lockUpdate     sync.RWMutex
}

func (mock *userRepoMock) Create(ctx context.Context, user *domain.User) (*domain.User, error) {
	if mock.CreateFunc == nil {
		panic("userRepoMock.CreateFunc: method is nil but userRepo.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *domain.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

func (mock *userRepoMock) CreateCalls() []struct {
	Ctx  context.Context
	User *domain.User
} {
	mock.lockCreate.RLock()
	calls := mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

func (mock *userRepoMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	if mock.GetByIDFunc == nil {
		panic("userRepoMock.GetByIDFunc: method is nil but userRepo.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

func (mock *userRepoMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	mock.lockGetByID.RLock()
	calls := mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

func (mock *userRepoMock) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	if mock.GetByEmailFunc == nil {
		panic("userRepoMock.GetByEmailFunc: method is nil but userRepo.GetByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(ctx, email)
}

func (mock *userRepoMock) GetByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	mock.lockGetByEmail.RLock()
	calls := mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

func (mock *userRepoMock) Update(ctx context.Context, id uuid.UUID, name *string, avatarURL *string) (*domain.User, error) {
	if mock.UpdateFunc == nil {
		panic("userRepoMock.UpdateFunc: method is nil but userRepo.Update was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        uuid.UUID
		Name      *string
		AvatarURL *string
	}{
		Ctx:       ctx,
		ID:        id,
		Name:      name,
		AvatarURL: avatarURL,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, name, avatarURL)
}

func (mock *userRepoMock) UpdateCalls() []struct {
	Ctx       context.Context
	ID        uuid.UUID
	Name      *string
	AvatarURL *string
} {
	mock.lockUpdate.RLock()
	calls := mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
