// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: examples.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBySense = `-- name: CountBySense :one
SELECT count(*) FROM examples WHERE sense_id = $1
`

func (q *Queries) CountBySense(ctx context.Context, senseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBySense, senseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExampleCustom = `-- name: CreateExampleCustom :one
INSERT INTO examples (id, sense_id, sentence, translation, source_slug, position, created_at)
VALUES ($1, $2, $3, $4, $5, COALESCE((SELECT MAX(position) FROM examples WHERE sense_id = $2), -1) + 1, $6)
RETURNING id, sense_id, ref_example_id, sentence, translation, source_slug, position, created_at
`

type CreateExampleCustomParams struct {
	ID          uuid.UUID
	SenseID     uuid.UUID
	Sentence    pgtype.Text
	Translation pgtype.Text
	SourceSlug  string
	CreatedAt   time.Time
}

func (q *Queries) CreateExampleCustom(ctx context.Context, arg CreateExampleCustomParams) (Example, error) {
	row := q.db.QueryRow(ctx, createExampleCustom,
		arg.ID,
		arg.SenseID,
		arg.Sentence,
		arg.Translation,
		arg.SourceSlug,
		arg.CreatedAt,
	)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.SenseID,
		&i.RefExampleID,
		&i.Sentence,
		&i.Translation,
		&i.SourceSlug,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createExampleFromRef = `-- name: CreateExampleFromRef :one
INSERT INTO examples (id, sense_id, ref_example_id, source_slug, position, created_at)
VALUES ($1, $2, $3, $4, COALESCE((SELECT MAX(position) FROM examples WHERE sense_id = $2), -1) + 1, $5)
RETURNING id, sense_id, ref_example_id, sentence, translation, source_slug, position, created_at
`

type CreateExampleFromRefParams struct {
	ID           uuid.UUID
	SenseID      uuid.UUID
	RefExampleID pgtype.UUID
	SourceSlug   string
	CreatedAt    time.Time
}

func (q *Queries) CreateExampleFromRef(ctx context.Context, arg CreateExampleFromRefParams) (Example, error) {
	row := q.db.QueryRow(ctx, createExampleFromRef,
		arg.ID,
		arg.SenseID,
		arg.RefExampleID,
		arg.SourceSlug,
		arg.CreatedAt,
	)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.SenseID,
		&i.RefExampleID,
		&i.Sentence,
		&i.Translation,
		&i.SourceSlug,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExample = `-- name: DeleteExample :execrows
DELETE FROM examples WHERE id = $1
`

func (q *Queries) DeleteExample(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExample, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExample = `-- name: UpdateExample :one
UPDATE examples
SET sentence = $2, translation = $3
WHERE id = $1
RETURNING id, sense_id, ref_example_id, sentence, translation, source_slug, position, created_at
`

type UpdateExampleParams struct {
	ID          uuid.UUID
	Sentence    pgtype.Text
	Translation pgtype.Text
}

func (q *Queries) UpdateExample(ctx context.Context, arg UpdateExampleParams) (Example, error) {
	row := q.db.QueryRow(ctx, updateExample, arg.ID, arg.Sentence, arg.Translation)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.SenseID,
		&i.RefExampleID,
		&i.Sentence,
		&i.Translation,
		&i.SourceSlug,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateExamplePosition = `-- name: UpdateExamplePosition :exec
UPDATE examples SET position = $2 WHERE id = $1
`

type UpdateExamplePositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateExamplePosition(ctx context.Context, arg UpdateExamplePositionParams) error {
	_, err := q.db.Exec(ctx, updateExamplePosition, arg.ID, arg.Position)
	return err
}
